const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'apps', 'web-client', 'src', 'App.tsx');
let content = fs.readFileSync(filePath, 'utf8');

const importRegex = /import \{ ArrowRight[^\}]*\} from 'lucide-react';/g;
content = content.replace(importRegex, "import { ArrowRight, CheckCircle2, Shield, Users, CreditCard, Sparkles, BarChart3, Globe2, Zap } from 'lucide-react';");

const heroStartIndex = content.indexOf('function Hero() {');
const appStartIndex = content.indexOf('function App() {');

if (heroStartIndex === -1 || appStartIndex === -1) {
  console.error("Could not find boundaries.");
  process.exit(1);
}

const newHero = `function Hero() {
  return (
    <div className="bg-slate-950 font-sans text-slate-300 selection:bg-primary-500/30 selection:text-primary-100 overflow-hidden">
      {/* Dynamic Glowing Background */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-[800px] pointer-events-none opacity-50 blur-3xl mix-blend-screen" style={{
        background: 'radial-gradient(circle at center, rgba(99, 102, 241, 0.15) 0%, rgba(16, 185, 129, 0.05) 40%, transparent 70%)'
      }}></div>

      {/* Hero Section */}
      <div className="relative pt-32 pb-20 sm:pt-40 sm:pb-24">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <motion.div 
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, ease: "easeOut" }}
          >
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-slate-900/50 border border-slate-800 text-sm text-primary-400 mb-8 backdrop-blur-md">
              <Sparkles className="h-4 w-4" /> Introducing TravelBooker 2.0
            </div>
            <h1 className="text-5xl sm:text-6xl md:text-7xl font-extrabold text-white tracking-tight mb-8 leading-tight">
              The OS for modern <br className="hidden sm:block"/>
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary-400 via-indigo-400 to-emerald-400">Travel Agencies</span>
            </h1>
            <p className="mt-4 text-xl sm:text-2xl text-slate-400 max-w-3xl mx-auto mb-12 font-light">
              Unify your bookings, manage vendor margins, and empower your agents with our all-in-one, enterprise-grade B2B platform.
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4 sm:gap-6">
              <Link to="/register" className="bg-gradient-to-r from-primary-600 to-indigo-600 text-white px-8 py-4 rounded-2xl text-lg font-semibold hover:shadow-lg hover:shadow-primary-500/25 transition-all transform hover:-translate-y-1 flex items-center justify-center gap-2">
                Start your 14-day free trial <ArrowRight className="h-5 w-5" />
              </Link>
              <Link to="/login" className="bg-slate-900/50 text-slate-300 border border-slate-700 px-8 py-4 rounded-2xl text-lg font-semibold hover:bg-slate-800 hover:text-white transition-all backdrop-blur-sm flex items-center justify-center">
                Agent Login
              </Link>
            </div>
          </motion.div>
        </div>
      </div>

      {/* Dashboard Mockup Showcase */}
      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-4 mb-32 z-10">
        <motion.div 
          initial={{ opacity: 0, y: 60 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, delay: 0.2, ease: "easeOut" }}
          className="rounded-[2rem] p-3 bg-gradient-to-b from-slate-800 to-slate-900/50 shadow-2xl shadow-indigo-500/10 border border-slate-800/50"
        >
          <div className="rounded-[1.5rem] overflow-hidden bg-slate-950 border border-slate-800 relative group">
            {/* The mock image generated by tool */}
            <img 
              src="/dashboard-mockup.png" 
              alt="TravelBooker Dashboard Interface" 
              className="w-full object-cover transform transition-transform duration-700 group-hover:scale-[1.02] opacity-90 group-hover:opacity-100" 
            />
            {/* Glass reflection overlay */}
            <div className="absolute inset-0 bg-gradient-to-tr from-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-700 pointer-events-none"></div>
          </div>
        </motion.div>
      </div>

      {/* Trusted By Banner */}
      <div className="border-y border-slate-800/50 bg-slate-900/20 backdrop-blur-sm py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <p className="text-center text-sm font-semibold text-slate-500 uppercase tracking-widest mb-8">Trusted by 500+ travel agencies worldwide</p>
          <div className="flex flex-wrap justify-center gap-12 sm:gap-24 opacity-40 grayscale hover:grayscale-0 transition-all duration-500">
             {/* Fake logos represented by icons and text for premium feel */}
             <div className="flex items-center gap-2"><Globe2 className="h-8 w-8"/> <span className="text-2xl font-bold tracking-tighter">WanderGroup</span></div>
             <div className="flex items-center gap-2"><Sparkles className="h-8 w-8"/> <span className="text-2xl font-bold tracking-tighter">OasisTravel</span></div>
             <div className="flex items-center gap-2"><Zap className="h-8 w-8"/> <span className="text-2xl font-bold tracking-tighter">NexusTours</span></div>
          </div>
        </div>
      </div>

      {/* Bento Box Features Section */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-32 relative">
        <div className="text-center mb-20">
          <h2 className="text-3xl sm:text-5xl font-bold text-white mb-6">Everything you need to <span className="text-primary-400">scale.</span></h2>
          <p className="text-xl text-slate-400 max-w-2xl mx-auto">Replace your fragmented spreadsheets with a unified, intelligent operating system.</p>
        </div>

        <div className="grid md:grid-cols-3 gap-6">
          {/* Large Feature 1 */}
          <div className="md:col-span-2 bg-gradient-to-br from-slate-900 to-slate-900/50 p-10 rounded-3xl border border-slate-800 hover:border-primary-500/50 transition-colors group">
            <div className="bg-primary-500/10 w-16 h-16 rounded-2xl flex items-center justify-center mb-8 border border-primary-500/20 group-hover:bg-primary-500/20 transition-colors">
              <BarChart3 className="h-8 w-8 text-primary-400" />
            </div>
            <h3 className="text-3xl font-bold text-white mb-4">Real-Time Ledger & Margin Engine</h3>
            <p className="text-lg text-slate-400 leading-relaxed mb-6">
              Automatically calculate vendor margins, track agent commissions, and reconcile payments across multiple currencies. Our double-entry ledger ensures your books are always perfectly balanced without manual data entry.
            </p>
          </div>

          {/* Small Feature 1 */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-900/50 p-10 rounded-3xl border border-slate-800 hover:border-indigo-500/50 transition-colors group">
            <div className="bg-indigo-500/10 w-16 h-16 rounded-2xl flex items-center justify-center mb-8 border border-indigo-500/20 group-hover:bg-indigo-500/20 transition-colors">
              <Users className="h-8 w-8 text-indigo-400" />
            </div>
            <h3 className="text-2xl font-bold text-white mb-4">Agent Workspaces</h3>
            <p className="text-slate-400 leading-relaxed">
              Create isolated workspaces for your agents. Control permissions, set custom commission rates, and track individual performance KPIs.
            </p>
          </div>

          {/* Small Feature 2 */}
          <div className="bg-gradient-to-br from-slate-900 to-slate-900/50 p-10 rounded-3xl border border-slate-800 hover:border-emerald-500/50 transition-colors group">
            <div className="bg-emerald-500/10 w-16 h-16 rounded-2xl flex items-center justify-center mb-8 border border-emerald-500/20 group-hover:bg-emerald-500/20 transition-colors">
              <Shield className="h-8 w-8 text-emerald-400" />
            </div>
            <h3 className="text-2xl font-bold text-white mb-4">Vendor Registry</h3>
            <p className="text-slate-400 leading-relaxed">
              Centralize your suppliers. Store contracts, track volume tiers, and auto-apply negotiated discounts directly at the checkout.
            </p>
          </div>

          {/* Large Feature 2 */}
          <div className="md:col-span-2 bg-gradient-to-br from-slate-900 to-slate-900/50 p-10 rounded-3xl border border-slate-800 hover:border-purple-500/50 transition-colors group relative overflow-hidden">
            <div className="absolute right-0 top-0 w-64 h-64 bg-purple-500/10 blur-3xl rounded-full pointer-events-none"></div>
            <div className="bg-purple-500/10 w-16 h-16 rounded-2xl flex items-center justify-center mb-8 border border-purple-500/20 group-hover:bg-purple-500/20 transition-colors relative z-10">
              <CreditCard className="h-8 w-8 text-purple-400" />
            </div>
            <h3 className="text-3xl font-bold text-white mb-4 relative z-10">Frictionless B2B Payments</h3>
            <p className="text-lg text-slate-400 leading-relaxed relative z-10">
              Issue invoices instantly, collect deposits, and manage corporate wallets. Handle refunds and partial payments seamlessly while keeping your cash flow transparent.
            </p>
          </div>
        </div>
      </div>

      {/* Pricing Section */}
      <div className="py-32 border-t border-slate-800/50 bg-slate-950 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-primary-900/20 blur-[120px] rounded-full pointer-events-none"></div>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="text-center mb-20">
            <h2 className="text-3xl sm:text-5xl font-bold text-white mb-6">Simple, scalable <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-emerald-600">pricing.</span></h2>
            <p className="text-xl text-slate-400 max-w-2xl mx-auto">No hidden fees. Cancel anytime. Choose the plan that grows with your agency.</p>
          </div>
          <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto items-center">
            
            {/* Starter Plan */}
            <div className="bg-slate-900/80 backdrop-blur-xl p-10 rounded-[2rem] border border-slate-800 flex flex-col hover:border-slate-700 transition-colors">
              <h3 className="text-xl font-medium text-slate-400 mb-2">Starter</h3>
              <div className="mb-6 flex items-baseline gap-2"><span className="text-5xl font-bold text-white">£49</span><span className="text-slate-500">/mo</span></div>
              <ul className="space-y-5 mb-10 flex-1">
                {['Up to 3 Agents', 'Basic CRM & Booking Engine', 'Standard Monthly Reporting', 'Email Support'].map((f, i) => (
                  <li key={i} className="flex items-center gap-3 text-slate-300"><CheckCircle2 className="h-5 w-5 text-slate-500" /> {f}</li>
                ))}
              </ul>
              <Link to="/register" className="block text-center w-full py-4 rounded-xl border border-slate-700 text-white font-semibold hover:bg-slate-800 transition-colors">Start Starter Plan</Link>
            </div>

            {/* Professional Plan (Highlighted) */}
            <div className="bg-gradient-to-b from-primary-900/40 to-slate-900 backdrop-blur-xl p-10 rounded-[2.5rem] border-2 border-primary-500/50 flex flex-col relative transform md:-translate-y-4 shadow-2xl shadow-primary-900/20">
              <div className="absolute -top-4 left-1/2 -translate-x-1/2 bg-gradient-to-r from-primary-500 to-indigo-500 text-white px-4 py-1.5 rounded-full text-sm font-bold tracking-wide shadow-lg">MOST POPULAR</div>
              <h3 className="text-xl font-medium text-primary-300 mb-2">Professional</h3>
              <div className="mb-6 flex items-baseline gap-2"><span className="text-6xl font-bold text-white">£149</span><span className="text-primary-400/70">/mo</span></div>
              <p className="text-slate-400 mb-8 border-b border-slate-800 pb-8">Everything in Starter, plus the tools to automate your finances.</p>
              <ul className="space-y-5 mb-10 flex-1">
                {['Unlimited Agents', 'Full Ledger Accounting', 'Margin Rules & Auto-markup', 'Vendor Management', 'Priority Support'].map((f, i) => (
                  <li key={i} className="flex items-center gap-3 text-slate-200"><CheckCircle2 className="h-5 w-5 text-primary-400" /> {f}</li>
                ))}
              </ul>
              <Link to="/register" className="block text-center w-full py-4 rounded-xl bg-gradient-to-r from-primary-600 to-indigo-600 text-white font-bold hover:shadow-lg hover:shadow-primary-600/30 transition-all hover:-translate-y-0.5">Start 14-Day Free Trial</Link>
            </div>

            {/* Enterprise Plan */}
            <div className="bg-slate-900/80 backdrop-blur-xl p-10 rounded-[2rem] border border-slate-800 flex flex-col hover:border-slate-700 transition-colors">
              <h3 className="text-xl font-medium text-slate-400 mb-2">Enterprise</h3>
              <div className="mb-6 flex items-baseline gap-2"><span className="text-5xl font-bold text-white">Custom</span></div>
              <ul className="space-y-5 mb-10 flex-1">
                {['White-labeling (Custom Domain)', 'Dedicated Account Manager', 'Custom API Integrations', 'SLA Guarantee 99.99%'].map((f, i) => (
                  <li key={i} className="flex items-center gap-3 text-slate-300"><CheckCircle2 className="h-5 w-5 text-slate-500" /> {f}</li>
                ))}
              </ul>
              <Link to="/register" className="block text-center w-full py-4 rounded-xl border border-slate-700 text-white font-semibold hover:bg-slate-800 transition-colors">Contact Sales</Link>
            </div>

          </div>
        </div>
      </div>

      {/* Bottom CTA */}
      <div className="border-t border-slate-800/50 bg-slate-900 py-24 text-center">
        <h2 className="text-4xl font-bold text-white mb-6">Ready to scale your agency?</h2>
        <p className="text-xl text-slate-400 mb-10">Join hundreds of agencies that are already using TravelBooker.</p>
        <Link to="/register" className="inline-flex bg-white text-slate-900 px-10 py-5 rounded-2xl text-xl font-bold hover:bg-slate-100 transition-colors shadow-xl shadow-white/10">
          Get Started For Free
        </Link>
      </div>
    </div>
  );
}
`;

const finalContent = content.substring(0, heroStartIndex) + newHero + '\n' + content.substring(appStartIndex);
fs.writeFileSync(filePath, finalContent, 'utf8');
console.log("Successfully rewrote Hero component to Premium SaaS.");
