// Full Airport dataset parsed from airport.text
export const AIRPORT_TEXT_MAP: Record<string, string> = {
  "AAL": "Aalborg Lufthavn Nørresundby Denmark",
  "AAR": "Aarhus Airport Tirstrup Denmark",
  "ABA": "Abakan International Airport Russia",
  "ABC": "Aeropuerto De Albacete Castilla-la Mancha Spain",
  "ABE": "Lehigh Valley International Airport Allentown Pennsylvania Pa Usa",
  "ABI": "Abilene Regional Airport Texas Tx Usa",
  "ABJ": "Aéroport International Félix Houphouët-boigny Airport Abidjan Port-bouet Ivory Coast",
  "ABQ": "Albuquerque International Sunport New Mexico Nm Usa",
  "ABV": "Nnamdi Azikiwe International Airport Abuja Nigeria",
  "ABZ": "Aberdeen International Airport Dyce Scotland Uk",
  "ACA": "Aeropuerto Internacional General Juan N. Álvarez International Airport Acapulco Guerrero Gr Mexico",
  "ACC": "Kotoka International Airport Accra Ghana",
  "ACE": "Aeropuerto De Lanzarote Arrecife Canary Islands Spain",
  "ACK": "Nantucket Memorial Airport Massachusetts Ma Usa",
  "ACY": "Atlantic City International Airport Egg Harbor Township New Jersey Nj Usa",
  "ADA": "Adana Havalimanı Çukurova Turkey",
  "ADD": "Addis Ababa Bole International Airport Ethiopia",
  "ADL": "Adelaide Airport South Australia Sa",
  "AEP": "Aeroparque Jorge Newbery Airfield Buenos Aires Palermo Argentina",
  "AER": "Sochi International Airport Russia",
  "AES": "Ålesund Lufthavn, Vigra Alesund Airport, Norway",
  "AEX": "Alexandria International Airport Louisiana La Usa",
  "AEY": "Akureyrarflugvöllur Akureyri Iceland",
  "AFW": "Fort Worth Alliance Airport Texas Tx Usa",
  "AGA": "Agadir–al Massira Airport Agadir Morocco",
  "AGB": "Flughafen Augsburg Affing Germany",
  "AGC": "Allegheny County Airport West Mifflin Pittsburgh Pennsylvania Pa Usa",
  "AGP": "Aeropuerto De Málaga-costa Del Sol Málaga Costa Spain",
  "AGS": "Augusta Regional Airport Georgia Ga Usa",
  "AGU": "Aeropuerto Internacional Lic. Jesús Terán Peredo International Airport Aguascalientes Ag Mexico",
  "AHB": "Abha Regional Airport Asir Province Saudi Arabia",
  "AJA": "Aéroport D’ajaccio-napoléon-bonaparte Ajaccio Napoleon Bonaparte Airport France",
  "AJF": "Al-jawf Domestic Airport Sakakah Al Jawf Province Saudi Arabia",
  "AJL": "Lengpui Airport Aizawl Aijal Mizoram Mz India",
  "AJU": "Aeroporto Aracaju–santa Maria Santa Aracaju Sergipe Se Brazil",
  "AKC": "Akron Fulton International Airport Ohio Oh Usa",
  "AKL": "Auckland Airport Mangere New Zealand",
  "AKT": "Royal Air Force Akrotiri Cyprus",
  "AKX": "Aktobe Airport Kazakhstan",
  "ALA": "Almaty International Airport Kazakhstan",
  "ALB": "Albany International Airport Colonie New York Ny Usa",
  "ALC": "Aeropuerto De Alicante-elche Alicante Valencia Spain",
  "ALG": "Houari Boumediene Airport Algiers Algeria",
  "ALS": "San Luis Valley Regional Airport Alamosa Colorado Co Usa",
  "AMA": "Rick Husband Amarillo International Airport Texas Tx Usa",
  "AMD": "Sardar Vallabhbhai Patel International Airport Ahmedabad Gujarat Gj India",
  "AMM": "Queen Alia International Airport Amman Zizya Jordan",
  "AMQ": "Bandar Udara Pattimura Airport Ambon Maluku Indonesia",
  "AMS": "Luchthaven Schiphol Amsterdam Netherlands",
  "ANC": "Ted Stevens Anchorage International Airport Alaska Ak Usa",
  "ANG": "Aéroport International D'angoulême-cognac Angoulême Champniers France",
  "ANR": "Internationale Luchthaven Antwerpen Antwerp Deurne Belgium",
  "ANS": "Aeropuerto Andahuaylas Apurímac Peru",
  "ANU": "V. C. Bird International Airport Saint John’s Antigua And Barbuda",
  "AOI": "Aeroporto Raffaello Sanzio Di Ancona-falconara Ancona Falconara Marittima Italy",
  "APA": "Centennial Airport Denver Aurora Colorado Co Usa",
  "APW": "Faleolo International Airport Apia Samoa",
  "AQJ": "King Hussein International Airport Aqaba Jordan",
  "AQP": "Aeropuerto Internacional Alférez Alfredo Rodríguez Ballón International Airport Arequipa Peru",
  "ARN": "Stockholm-arlanda Flygplats Stockholm Arlanda Sweden",
  "ART": "Watertown International Airport New York Ny Usa",
  "ASB": "Ashgabat International Airport Turkmenistan",
  "ASE": "Aspen–pitkin County Airport Aspen Colorado Co Usa",
  "ASM": "Asmara International Airport Eritrea",
  "ASU": "Aeropuerto Internacional Silvio Pettirossi Asunción Luque Paraguay",
  "ATA": "Aeropuerto Comandante Fap Germán Arias Graziani Airport Huaraz Anta Ancash Peru",
  "ATH": "Athens International Airport, Eleftherios Venizelos Greece",
  "ATL": "Hartsfield–jackson International Airport Atlanta Georgia Ga Usa",
  "ATQ": "Sri Guru Ram Das Jee International Airport Amritsar Punjab Pb India",
  "ATW": "Appleton International Airport Greenville Wisconsin Wi Usa",
  "AUA": "Internationale Luchthaven Koningin Beatrix Queen Oranjestad Aruba Netherlands",
  "AUH": "Abu Dhabi International Airport United Arab Emirates",
  "AUS": "Austin–bergstrom International Airport Austin Texas Tx Usa",
  "AVL": "Asheville Regional Airport North Carolina Nc Usa",
  "AVP": "Wilkes-barre/scranton International Airport Avoca Scranton Pennsylvania Pa Usa",
  "AWZ": "Ahvaz International Airport Ahwaz Iran",
  "AYP": "Aeropuerto Coronel Fap Alfredo Mendívil Duarte Airport Ayacucho Peru",
  "AYT": "Antalya Havalimanı Turkey",
  "AZA": "Mesa Gateway Airport Arizona Az Usa",
  "AZO": "Kalamazoo/battle Creek International Airport Kalamazoo Battle Michigan Mi Usa",
  "BAH": "Bahrain International Airport Muharraq",
  "BAL": "Batman Havaalanı Turkey",
  "BAQ": "Aeropuerto Internacional Ernesto Cortissoz International Airport Barranquilla Soledad Colombia",
  "BAT": "Aeroporto Chafei Amsei Airport Barretos Sao Paulo São Sp Brazil",
  "BCB": "Virginia Tech Montgomery Executive Airport Blacksburg Christiansburg Va Usa",
  "BCD": "Paliparan Ng Bacolod–silay Airport Bacolod Philippines",
  "BCN": "Aeropuerto De Barcelona-el Prat Barcelona El Llobregat Spain",
  "BDA": "L.f. Wade International Airport Bermuda St. David's Island Uk",
  "BDI": "Bird Island Airport Seychelles",
  "BDL": "Bradley International Airport Hartford Windsor Locks Connecticut Ct Usa",
  "BDO": "Bandar Udara Internasional Husein Sastranegara International Airport Bandung West Java Indonesia",
  "BDS": "Brindisi - Aeroporto Del Salento Italy",
  "BEB": "Port-adhair Beinn Na Faoghla Benbecula Balivanich Scotland Uk",
  "BED": "Laurence G. Hanscom Field Bedford Massachusetts Ma Usa",
  "BEG": "Aerodrom Beograd - Nikola Tesla Belgrade Serbia",
  "BEL": "Aeroporto Internacional Júlio Cezar Ribeiro Belém Val De Cans Pará Pa Brazil",
  "BER": "Flughafen Berlin Brandenburg Germany",
  "BES": "Brest Bretagne Airport France",
  "BEY": "Beirut–rafic Hariri International Airport Beirut Lebanon",
  "BFF": "Western Nebraska Regional Airport Scottsbluff Ne Usa",
  "BFI": "King County International Airport / Boeing Field Seattle Washington Wa Usa",
  "BFL": "Meadows Field Airport Bakersfield Oildale California Ca Usa",
  "BFS": "Belfast International Airport Aldergrove Northern Ireland Uk",
  "BGA": "Aeropuerto Internacional De Palonegro International Airport Bucaramanga Lebrija Colombia",
  "BGI": "Grantley Adams International Airport Bridgetown Seawell Barbados",
  "BGO": "Bergen Lufthavn, Flesland Norway",
  "BGR": "Bangor International Airport Maine Me Usa",
  "BGW": "Baghdad International Airport Iraq",
  "BGY": "Aeroporto Di Bergamo-orio Al Serio Il Caravaggio International Airport Bergamo Milan Italy",
  "BHD": "George Best Belfast City Airport Northern Ireland Uk",
  "BHM": "Birmingham–shuttlesworth International Airport Birmingham Alabama Al Usa",
  "BHO": "Raja Bhoj Airport Bhopal Madhya Pradesh Mp India",
  "BHX": "Birmingham Airport England Uk",
  "BIK": "Bandar Udara Internasional Frans Kaisiepo International Airport Biak Indonesia",
  "BIL": "Billings Logan International Airport Montana Mt Usa",
  "BIO": "Aeropuerto De Bilbao Biscay Spain",
  "BJC": "Rocky Mountain Metropolitan Airport Denver Colorado Co Usa",
  "BJL": "Banjul International Airport The Gambia",
  "BJM": "Aéroport International De Bujumbura Burundi",
  "BJX": "Aeropuerto Internacional De Guanajuato Silao Mexico",
  "BKF": "Lake Brooks Seaplane Base Katmai National Park Camp Alaska Ak Usa",
  "BKI": "Lapangan Terbang Antarabangsa Kota Kinabalu Sabah Malaysia",
  "BKK": "Suvarnabhumi Airport Bangkok Thailand",
  "BKL": "Burke Lakefront Airport Cleveland Ohio Oh Usa",
  "BKO": "Aéroport International De Bamako–sénou Senou Airport Bamako Mali",
  "BLI": "Bellingham International Airport Washington Wa Usa",
  "BLK": "Blackpool Airport England Uk",
  "BLL": "Billund Lufthavn Denmark",
  "BLQ": "Aeroporto Di Bologna-guglielmo Marconi Guglielmo Bologna Italy",
  "BLR": "Kempegowda International Airport Bengaluru Devanahalli Karnataka Ka India",
  "BMA": "Stockholm-bromma Flygplats Stockholm Bromma Sweden",
  "BMI": "Central Illinois Regional Airport Bloomington Il Usa",
  "BMV": "Sân Bay Buôn Ma Thuột Buon Thuot Vietnam",
  "BNA": "Nashville International Airport Tennessee Tn Usa",
  "BND": "Bandar Abbas International Airport Iran",
  "BNE": "Brisbane Airport Queensland Qld Australia",
  "BNX": "Banja Luka International Airport Mahovljani Bosnia And Herzegovina",
  "BOB": "Bora Airport Motu Mute French Polynesia France",
  "BOD": "Aéroport De Bordeaux-mérignac Bordeaux Mérignac France",
  "BOG": "Aeropuerto Internacional El Dorado International Airport Bogotá Colombia",
  "BOH": "Bournemouth Airport Hurn England Uk",
  "BOI": "Boise Airport Idaho Id Usa",
  "BOM": "Chhatrapati Shivaji International Airport Mumbai Maharashtra Mh India",
  "BON": "Luchthaven Flamingo International Airport Bonaire Kralendijk Abc Islands Netherlands",
  "BOS": "Logan International Airport Boston Paradise Massachusetts Ma Usa",
  "BPN": "Bandar Udara Internasional Sultan Aji Muhammad Sulaiman Balikpapan East Kalimantan Indonesia",
  "BPT": "Jack Brooks Regional Airport Beaumont Port Arthur Texas Tx Usa",
  "BQH": "Biggin Hill Airport London Bromley England Uk",
  "BRA": "Aeroporto De Barreiras Bahia Ba Brazil",
  "BRC": "Aeropuerto De San Carlos Bariloche Airport Argentina",
  "BRE": "Flughafen Bremen Germany",
  "BRI": "Aeroporto Di Bari-karol Wojtyła Bari Palese Italy",
  "BRO": "Brownsville/south Padre Island International Airport Brownsville South Texas Tx Usa",
  "BRQ": "Letiště Brno–tuřany Brno Tuřany Czech Republic",
  "BRR": "Port-adhair Bharraigh Barra Outer Hebrides Scotland Uk",
  "BRS": "Bristol Airport Lulsgate Bottom England Uk",
  "BRU": "Luchthaven Brussel-nationaal Brussels Belgium",
  "BRW": "Wiley Post–will Rogers Memorial Airport Barrow Alaska Ak Usa",
  "BSB": "Aeroporto Internacional De Brasília–pres. Juscelino Kubitschek Presidente International Airport Brasília Brazil",
  "BSL": "Euroairport Basel–mulhouse–freiburg Basel Saint-louis France Switzerland",
  "BTJ": "Bandar Udara Internasional Sultan Iskandar Muda Iskander International Airport Banda Aceh Blang Bintang Indonesia",
  "BTM": "Bert Mooney Airport Butte Montana Mt Usa",
  "BTR": "Baton Rouge Metropolitan Airport Louisiana La Usa",
  "BTS": "Letisko M. R. Štefánika Štefánik Airport Bratislava Slovakia",
  "BTV": "Burlington International Airport Vermont Vt Usa",
  "BUD": "Budapest Liszt Ferenc Nemzetközi Repülőtér Hungary",
  "BUF": "Buffalo Niagara International Airport Cheektowaga New York Ny Usa",
  "BUR": "Bob Hope Airport Burbank Los Angeles California Ca Usa",
  "BUT": "Bathpalathang Airport Jakar Bhutan",
  "BVA": "Aéroport De Beauvais-tillé Beauvais Tillé France",
  "BVB": "Aeroporto International Atlas Brasil Cantanhede Boa Vista Roraima Rr Brazil",
  "BVC": "Aeroporto Internacional Aristides Pereira International Airport Sal Rei Boa Vista Cape Verde",
  "BWE": "Flughafen Braunschweig-wolfsburg Braunschweig Wolfsburg Germany",
  "BWF": "Barrow/walney Island Airport Barrow-in-furness England Uk",
  "BWI": "Baltimore/washington International Thurgood Marshall Airport Baltimore Washington D.c. Maryland Md Usa",
  "BWN": "Brunei International Airport Bandar Seri Begawan",
  "BYJ": "Aeroporto De Beja Portugal",
  "BZE": "Philip S. W. Goldson International Airport Belize City Ladyville",
  "BZN": "Bozeman Yellowstone International Airport Belgrade Montana Mt Usa",
  "BZV": "Maya-maya Airport Brazzaville Congo Republic Of The",
  "CAE": "Columbia Metropolitan Airport Cayce South Carolina Sc Usa",
  "CAG": "International Aeroporto Di Cagliari Elmas Airport Sardinia Italy",
  "CAH": "Sân Bay Cà Mau Ca Airport Vietnam",
  "CAI": "Cairo International Airport Egypt",
  "CAK": "Akron–canton Airport Akron Canton Ohio Oh Usa",
  "CAN": "Guangzhou Baiyun International Airport Canton Guangdong China",
  "CBB": "Aeropuerto Internacional Jorge Wilstermann Cochabamba Bolivia",
  "CBG": "Cambridge Airport Teversham England Uk",
  "CBQ": "Margaret Ekpo International Airport Calabar Nigeria",
  "CBR": "Canberra International Airport Queanbeyan Australian Capital Territory Act Australia",
  "CCF": "Aéroport De Carcassonne France",
  "CCJ": "Calicut International Airport Karipur Kozhikode Kerala Kl India",
  "CCK": "Cocos (keeling) Islands Airport West Island Australia",
  "CCP": "Aeropuerto Carriel Sur International Airport Concepción Chile",
  "CCS": "Aeropuerto Internacional De Maiquetia “simón Bolívar” Simón Bolívar International Airport Caracas Maiquetía Venezuela",
  "CCU": "Netaji Subhas Chandra Bose International Airport Kolkata Calcutta West Bengal Wb India",
  "CDC": "Cedar City Regional Airport Utah Ut Usa",
  "CDF": "Maes Awyr Caerdydd Cardiff Wales Uk",
  "CDG": "Aéroport De Paris-charles-de-gaulle Charles Gaulle Airport Paris France",
  "CEB": "Paliparang Pandaigdig Ng Mactan–cebu International Airport Cebu Lapu-lapu City Philippines",
  "CEK": "Chelyabinsk Airport Russia",
  "CFB": "Aeroporto Internacional De Cabo Frio Rio Janeiro Rj Brazil",
  "CFD": "Coulter Field Bryan Texas Tx Usa",
  "CFN": "Aerfort Dhún Na Ngall Carrickfinn Donegal Ireland",
  "CGH": "Aeroporto De São Paulo/congonhas Congonhas Airport Paulo Sao Sp Brazil",
  "CGK": "Bandar Udara Internasional Soekarno–hatta International Airport Jakarta Tangerang Banten Indonesia",
  "CGN": "Flughafen Köln/bonn Cologne Bonn Germany",
  "CGO": "Zhengzhou Xinzheng International Airport Henan China",
  "CGP": "Shah Amanat International Airport Chittagong Patenga Bangladesh",
  "CGR": "Aeroporto Internacional De Campo Grande Mato Grosso Do Sul Ms Brazil",
  "CHA": "Chattanooga Metropolitan Airport Tennessee Tn Usa",
  "CHC": "Christchurch International Airport Harewood New Zealand",
  "CHM": "Aeropuerto Teniente Fap Jaime Montreuil Morales Airport Chimbote Ancash Peru",
  "CHO": "Charlottesville–albemarle Airport Charlottesville Virginia Va Usa",
  "CHR": "Aéroport De Châteauroux-centre Châteauroux France",
  "CHS": "Charleston International Airport North South Carolina Sc Usa",
  "CIA": "Ciampino–aeroporto Internazionale G. B. Pastine Rome Ciampino Italy",
  "CID": "The Eastern Iowa Airport Cedar Rapids Ia Usa",
  "CIT": "Shymkent International Airport Kazakhstan",
  "CIU": "Chippewa County International Airport Sault Ste. Marie Michigan Mi Usa",
  "CIX": "Aeropuerto Internacional Capitán Fap José Abelardo Quiñones Gonzáles Chiclayo Lambayeque Peru",
  "CJA": "Aeropuerto Mayor General Fap Armando Revoredo Iglesias Airport Cajamarca Peru",
  "CJU": "Jeju International Airport Cheju Korea South",
  "CKB": "North Central West Virginia Airport Clarksburg Bridgeport Wv Usa",
  "CKG": "Chongqing Jiangbei International Airport Yubei District China",
  "CKY": "Conakry International Airport Guinea",
  "CLD": "Mcclellan-palomar Airport Carlsbad California Ca Usa",
  "CLE": "Hopkins International Airport Cleveland Ohio Oh Usa",
  "CLJ": "Aeroportul International “avram Iancu” Cluj Cluj-napoca Romania",
  "CLL": "Easterwood Airport College Station Texas Tx Usa",
  "CLO": "Aeropuerto Internacional Alfonso Bonilla Aragón International Airport Santiago De Cali Colombia",
  "CLT": "Douglas International Airport Charlotte North Carolina Nc Usa",
  "CLY": "Aéroport De Calvi – Sainte-catherine Airport France",
  "CMB": "Bandaranaike International Airport Colombo Katunayake Western Province Sri Lanka",
  "CMH": "Port Columbus International Airport Ohio Oh Usa",
  "CMI": "University Of Illinois Willard Airport Champaign-urbana Savoy Il Usa",
  "CMN": "Mohammed V International Airport Casablanca Nouasseur Morocco",
  "CMX": "Houghton County Memorial Airport Calumet Michigan Mi Usa",
  "CNF": "Aeroporto Internacional Tancredo Neves - Confins Neves/confins Belo Horizonte Minas Gerais Mg Brazil",
  "CNG": "Base Aérienne 709 Cognac-châteaubernard Cognac Châteaubernard France",
  "CNN": "Kannur International Airport Thalassery Kerala Kl India",
  "CNS": "Cairns Airport Queensland Qld Australia",
  "CNX": "Chiang Mai International Airport Lamphun Thailand",
  "COK": "Cochin International Airport Kochi Kerala Kl India",
  "COO": "Aéroport International De Cotonou Benin",
  "COR": "Aeropuerto Internacional De Córdoba Ingeniero Aeronáutico Ambrosio L.v. Taravella Cordoba Argentina",
  "COS": "Colorado Springs Airport Co Usa",
  "CPH": "Københavns Lufthavn, Kastrup Copenhagen Tårnby Denmark",
  "CPR": "Casper–natrona County International Airport Casper Natrona Wyoming Wy Usa",
  "CPT": "Cape Town International Airport South Africa",
  "CPV": "Aeroporto Presidente João Suassuna Airport Campina Grande Paraíba Pb Brazil",
  "CQM": "Aeropuerto Central Ciudad Real Puertollano Spain",
  "CRK": "Paliparang Pandaigdig Ng Clark International Airport Manila Mabalacat City Philippines",
  "CRL": "Aéroport De Charleroi Bruxelles Sud Brussels South Airport Gosselies Belgium",
  "CRP": "Corpus Christi International Airport Texas Tx Usa",
  "CRW": "Yeager Airport Charleston West Virginia Wv Usa",
  "CTA": "Aeroporto Di Catania-fontanarossa Catania Italy",
  "CTG": "Aeropuerto Internacional Rafael Núñez Cartagena Bolívar Colombia",
  "CTS": "New Chitose Airport Sapporo Japan",
  "CTU": "Chengdu Shuangliu International Airport Sichuan China",
  "CUL": "Aeropuerto Internacional Federal De Bachigualato International Airport Culiacán Navolato Sinaloa Si Mexico",
  "CUN": "Aeropuerto Internacional De Cancún Quintana Roo Qr Mexico",
  "CUR": "Hato Internationale Luchthaven Curaçao International Airport Willemstad Netherlands",
  "CUZ": "Aeropuerto Internacional Alejandro Velasco Astete International Airport Cusco Peru",
  "CVF": "Altiport De Courchevel French Alps France",
  "CVG": "Cincinnati/northern Kentucky International Airport Hebron Ohio Ky Usa",
  "CVU": "Aeródromo De Corvo Vila Do Azores Portugal",
  "CWB": "Aeroporto Internacional De Curitiba - Afonso Pena International Airport São José Dos Pinhais Paraná Pr Brazil",
  "CWL": "Maes Awyr Caerdydd Cardiff Wales Uk",
  "CXR": "Sân Bay Quốc Tế Cam Ranh International Airport Khanh Hoa Vietnam",
  "CZM": "Aeropuerto Internacional De Cozumel International Airport Quintana Roo Qr Mexico",
  "CZS": "Aeroporto Internacional De Cruzeiro Do Sul International Airport Acre Ac Brazil",
  "DAB": "Daytona Beach International Airport Florida Fl Usa",
  "DAC": "Hazrat Shahjalal International Airport Dhaka Kurmitola Bangladesh",
  "DAD": "Sân Bay Quốc Tế Đà Nẵng Da Nang Vietnam",
  "DAL": "Dallas Love Field Fort Worth Texas Tx Usa",
  "DAM": "Damascus International Airport Syria",
  "DAR": "Julius Nyerere International Airport Es Salaam Tanzania",
  "DAY": "James M. Cox Dayton International Airport Ohio Oh Usa",
  "DBQ": "Dubuque Regional Airport Iowa Ia Usa",
  "DBV": "Zračna Luka Dubrovnik/čilipi Dubrovnik Čilipi Croatia",
  "DCA": "Ronald Reagan Washington National Airport D.c. Arlington County Virginia Va Usa",
  "DEB": "Debreceni Nemzetközi Repülőtér Debrecen Hungary",
  "DED": "Jolly Grant International Airport Dehradun Uttarakhand Uk India",
  "DEL": "Indira Gandhi International Airport New Delhi Dl India",
  "DEN": "Denver International Airport Colorado Co Usa",
  "DET": "Coleman A. Young International Airport Detroit Michigan Mi Usa",
  "DFW": "Dallas/fort Worth International Airport Dallas–fort Fort Texas Tx Usa",
  "DIL": "Aeroporto Internacional Presidente Nicolau Lobato International Airport Dili Timor-leste East Timor",
  "DIN": "Sân Bay Điện Biên Phủ Dien Bien Phu Vietnam",
  "DKR": "Léopold Sédar Senghor International Airport Dakar Yoff Senegal",
  "DLA": "Aéroport International De Douala Cameroon",
  "DLC": "Dalian Zhoushuizi International Airport Liaoning China",
  "DLH": "Duluth International Airport Minnesota Mn Usa",
  "DLI": "Lien Khuong Airport Dalat Đức Trọng Lâm Đồng Vietnam",
  "DLM": "Dalaman Havalimanı Turkey",
  "DME": "Domodedovo International Airport Moscow Russia",
  "DMK": "Don Mueang International Airport Bangkok Thailand",
  "DMM": "King Fahd International Airport Dammam Eastern Province Saudi Arabia",
  "DND": "Port-adhair Dhùn Dèagh Dundee Scotland Uk",
  "DNK": "Dnipropetrovsk International Airport Ukraine",
  "DNR": "Aéroport De Dinard–pleurtuit–saint-malo Airport Saint-malo Pleurtuit France",
  "DOH": "Hamad International Airport Doha Qatar",
  "DOM": "Douglas–charles Airport Melville Hall Marigot Roseau Dominica",
  "DPS": "Bandar Udara Internasional Ngurah Rai International Airport Denpasar Badung Bali Indonesia",
  "DRO": "Durango–la Plata County Airport Durango Colorado Co Usa",
  "DRS": "Flughafen Dresden Airport Saxony Germany",
  "DRW": "Darwin International Airport Darwn Marrara Northern Territory Nt Australia",
  "DSA": "Robin Hood Airport Doncaster Sheffield Finningley England Uk",
  "DSI": "Destin Executive Airport Florida Fl Usa",
  "DSM": "Des Moines International Airport Iowa Ia Usa",
  "DSS": "Blaise Diagne International Airport Dakar Ndiass Senegal",
  "DTM": "Flughafen Dortmund Germany",
  "DTN": "Shreveport Downtown Airport Louisiana La Usa",
  "DTW": "Detroit Metropolitan Wayne County Airport Michigan Mi Usa",
  "DUB": "Aerfort Bhaile Átha Cliath Dublin Collinstown Ireland",
  "DUD": "Dunedin International Airport Momona New Zealand",
  "DUS": "Flughafen Düsseldorf Dusseldorf Germany",
  "DVO": "Paliparang Pandaigdig Ng Francisco Bangoy International Airport Davao City Catitipan Mindanao Philippines",
  "DWC": "Al Maktoum International Airport Dubai Jebel Ali United Arab Emirates",
  "DXB": "Dubai International Airport Al Garhoud United Arab Emirates",
  "DXR": "Danbury Municipal Airport Connecticut Ct Usa",
  "DYU": "Dushanbe International Airport Tajikistan",
  "DZA": "Aéroport De Dzaoudzi-pamandzi Dzaoudzi Pamandzi Mayotte France",
  "EAS": "Aeropuerto De San Sebastián Hondarribia Spain",
  "EAT": "Pangborn Memorial Airport Wenatchee Washington Wa Usa",
  "EBB": "Entebbe International Airport Kampala Uganda",
  "EBL": "Erbil International Airport Iraq",
  "ECP": "Northwest Florida Beaches International Airport Panama City Fl Usa",
  "EDI": "Port-adhair Dhùn Èideann Edinburgh Scotland Uk",
  "EGC": "Aéroport De Bergerac Dordogne Périgord France",
  "EGE": "Eagle County Regional Airport Gypsum Colorado Co Usa",
  "EIN": "Vliegbasis Eindhoven Netherlands",
  "ELP": "El Paso International Airport Texas Tx Usa",
  "EMA": "East Midlands Airport Nottingham Castle Donington England Uk",
  "ENK": "Enniskillen St. Angelo Airport Northern Ireland Uk",
  "ENS": "Enschede Vliegbasis Twente Netherlands",
  "ENU": "Akanu Ibiam International Airport Enugu Nigeria",
  "EOH": "Aeropuerto Olaya Herrera Airport Medellín Colombia",
  "ERI": "Erie International Airport Pennsylvania Pa Usa",
  "ESB": "Esenboğa Uluslararası Havalimanı Ankara Esenboga Turkey",
  "EUG": "Eugene Airport Oregon Or Usa",
  "EUX": "F. D. Roosevelt Airport Sint Eustatius Oranjestad Netherlands",
  "EVE": "Harstad-narvik Lufthavn, Evenes Narvik Norway",
  "EVN": "Zvart'nots' Mijazgayin Odanavakayan Yerevan Zvartnots Armenia",
  "EWR": "Liberty International Airport Newark New Jersey Nj Usa",
  "EXT": "Exeter International Airport Devon England Uk",
  "EYW": "Key West International Airport Florida Fl Usa",
  "EZE": "Aeropuerto Internacional Ministro Pistarini Buenos Aires Ezeiza Argentina",
  "FAE": "Vága Floghavn Vágar Airport Sørvágur Tórshavn Faroe Islands Denmark",
  "FAO": "Aeroporto Internacional De Faro Algarve Portugal",
  "FAR": "Hector International Airport Fargo Moorhead North Dakota Nd Usa",
  "FAT": "Fresno Yosemite International Airport California Ca Usa",
  "FCA": "Glacier Park International Airport Kalispell Flathead County Montana Mt Usa",
  "FCO": "Fiumicino – Aeroporto Internazionale Leonardo Da Vinci Rome Italy",
  "FDF": "Aéroport International Martinique Aimé Césaire Fort-de-france Le Lamentin France",
  "FDH": "Flughafen Friedrichshafen Lake Constance Germany",
  "FEZ": "Fes–saïss Airport Fes Saiss Morocco",
  "FFA": "First Flight Airport Kill Devil Hills North Carolina Nc Usa",
  "FIE": "Fair Isle Airport Shetland Scotland Uk",
  "FIH": "N'djili International Airport Kinshasa Congo Democratic Republic Of The",
  "FKB": "Flughafen Karlsruhe/baden-baden Baden Airpark Rheinmünster Karlsruhe Germany",
  "FKL": "Venango Regional Airport Franklin Oil City Pennsylvania Pa Usa",
  "FLG": "Flagstaff Pulliam Airport Arizona Az Usa",
  "FLL": "Fort Lauderdale–hollywood International Airport Lauderdale Miami Florida Fl Usa",
  "FLN": "Aeroporto Internacional De Florianópolis–hercílio Luz Hercílio Florianópolis Florianopolis Santa Catarina Sc Brazil",
  "FLR": "Aeroporto Di Firenze-peretola Florence Peretola Tuscany Italy",
  "FLW": "Aeroporto Das Flores Santa Cruz Azores Portugal",
  "FMM": "Allgäu-airport Memmingen Germany",
  "FMN": "Four Corners Regional Airport Farmington New Mexico Nm Usa",
  "FMO": "Flughafen Münster/osnabrück Münster Osnabrück Nrw Germany",
  "FNA": "Lungi International Airport Freetown Sierra Leone",
  "FNC": "Aeroporto Da Madeira Cristiano Ronaldo International Airport Funchal Santa Catarina Região Autónoma Portugal",
  "FNJ": "Pyongyang International Airport North Korea",
  "FNT": "Bishop International Airport Flint Michigan Mi Usa",
  "FOC": "Fuzhou Changle International Airport Zhanggang China",
  "FOD": "Fort Dodge Regional Airport Iowa Ia Usa",
  "FOR": "Aeroporto Internacional Pinto Martins International Airport Fortaleza Ceará Ce Brazil",
  "FPO": "Grand Bahama International Airport Freeport Bahamas",
  "FRA": "Flughafen Frankfurt Am Main Germany",
  "FRS": "Aeropuerto Internacional Mundo Maya International Airport Flores Guatemala",
  "FRU": "Manas International Airport Bishkek Kyrgyzstan",
  "FSC": "Aéroport Figari-sud Corse Porto-vecchio Figari France",
  "FSD": "Sioux Falls Regional Airport South Dakota Sd Usa",
  "FSP": "Aéroport De Saint-pierre Saint-pierre, Saint Pierre And Miquelon France",
  "FSZ": "Shizuoka Airport Makinohara Japan",
  "FUE": "Aeropuerto De Fuerteventura El Matorral Canary Islands Spain",
  "FUK": "Fukuoka Airport Japan",
  "FUN": "Funafuti International Airport Tuvalu",
  "FWA": "Fort Wayne International Airport Indiana In Usa",
  "GAI": "Montgomery County Airpark Gaithersburg Maryland Md Usa",
  "GAN": "International Airport Addu Atoll Maldives",
  "GAU": "Lokpriya Gopinath Bordoloi International Airport Guwahati Gowhatty Assam As India",
  "GBE": "Sir Seretse Khama International Airport Gaborone Botswana",
  "GCC": "Northeast Wyoming Regional Airport Gillette Wy Usa",
  "GCI": "Guernsey Airport Forest Channel Islands Uk",
  "GCM": "Owen Roberts International Airport George Town Grand Cayman England Islands Uk",
  "GCW": "Grand Canyon West Airport Peach Springs Arizona Az Usa",
  "GDL": "Aeropuerto Internacional De Guadalajara Jalisco Jal Mexico",
  "GDN": "Port Lotniczy Gdańsk Im. Lecha Wałęsy Poland",
  "GDR": "Aeroporto De Angra Dos Reis - Carmelo Jordão Airport Rio Janeiro Rj Brazil",
  "GEG": "Spokane International Airport Washington Wa Usa",
  "GEO": "Cheddi Jagan International Airport Georgetown Timehri Guyana",
  "GGG": "East Texas Regional Airport Gregg County Tx Usa",
  "GGT": "Exuma International Airport Great Moss Town Bahamas",
  "GIB": "Gibraltar International Airport Uk",
  "GIG": "Aeroporto Internacional Do Galeão–antonio Carlos Jobim International Airport Rio De Janeiro Rj Brazil",
  "GIZ": "King Abdullah Bin Abdulaziz Airport Jizan Gizan Province Saudi Arabia",
  "GJT": "Grand Junction Regional Airport Colorado Co Usa",
  "GLA": "Port-adhair Eadar-nàiseanta Ghlaschu Glasgow Scotland Uk",
  "GLO": "Gloucestershire Airport Gloucester Staverton England Uk",
  "GLU": "Gelephu Airport Bhutan",
  "GMP": "Gimpo International Airport Seoul Gangseo District Korea South",
  "GMU": "Greenville Downtown Airport South Carolina Sc Usa",
  "GMZ": "Aeropuerto De La Gomera Playa Santiago Canary Islands Spain",
  "GND": "Maurice Bishop International Airport St. George’s Point Salines Grenada",
  "GNV": "Gainesville Regional Airport Florida Fl Usa",
  "GOA": "Aeroporto Di Genova Cristoforo Colombo Airport Genoa Italy",
  "GOH": "Nuuk Lufthavn Greenland Denmark",
  "GOI": "Goa International Airport Dabolim Ga India",
  "GOJ": "Strigino Nizhny Novgorod International Airport Gorky Russia",
  "GOQ": "Golmud Airport Qinghai China",
  "GOT": "Göteborg Landvetter Airport Gothenburg Sweden",
  "GOV": "Gove Airport Nhulunbuy Peninsula Northern Territory Nt Australia",
  "GPS": "Seymour Airport Baltra Galápagos Islands Ecuador",
  "GPT": "Gulfport–biloxi International Airport Biloxi Mississippi Ms Usa",
  "GRB": "Austin Straubel International Airport Green Bay Wisconsin Wi Usa",
  "GRK": "Killeen–fort Hood Regional Airport Killeen Fort Texas Tx Usa",
  "GRO": "Aeropuerto De Girona-costa Brava Girona Costa Spain",
  "GRR": "Gerald R. Ford International Airport Grand Rapids Michigan Mi Usa",
  "GRU": "Aeroporto Internacional Guarulhos–governador André Franco Montoro International Airport São Paulo Sao Sp Brazil",
  "GRW": "Aeroporto De Graciosa Santa Cruz Azores Portugal",
  "GRX": "Aeropuerto Federico García Lorca Granada-jaén Airport Granada Jaén Spain",
  "GRZ": "Flughafen Graz Austria",
  "GSO": "Piedmont Triad International Airport Greensboro North Carolina Nc Usa",
  "GSP": "Greenville–spartanburg International Airport Greenville Spartanburg South Carolina Sc Usa",
  "GST": "Gustavus Airport Alaska Ak Usa",
  "GTR": "Golden Triangle Regional Airport Columbus Starkville Mississippi Ms Usa",
  "GUA": "Aeropuerto Internacional La Aurora International Airport Guatemala City",
  "GUC": "Gunnison–crested Butte Regional Airport Gunnison Colorado Co Usa",
  "GUM": "Antonio B. Won Pat International Airport Barrigada And Tamuning Guam Usa",
  "GUR": "Gurney Airport Alotau Papua New Guinea",
  "GUW": "Atma Atyrau Airport Kazakhstan",
  "GVA": "Aéroport International De Genève Geneva Meyrin Switzerland",
  "GWY": "Galway Airport Carnmore Ireland",
  "GYD": "Heydar Aliyev International Airport Baku Azerbaijan",
  "GYE": "Aeropuerto Internacional José Joaquín De Olmedo Guayaquil Guayas Ecuador",
  "GYN": "Aeroporto Internacional Santa Genoveva International Airport Goiânia Goiania Goiás Go Brazil",
  "GZA": "Yasser Arafat International Airport Gaza Palestine",
  "HAH": "Prince Said Ibrahim International Airport Moroni Hahaya Comoros",
  "HAJ": "Flughafen Hannover-langenhagen Hannover Langenhagen Germany",
  "HAK": "Haikou Meilan International Airport Hainan China",
  "HAM": "Flughafen Hamburg Helmut Schmidt Germany",
  "HAN": "Nội Bài International Airport Hanoi Vietnam",
  "HAQ": "Hanimaadhoo International Airport Haa Dhaalu Atoll Maldives",
  "HAV": "Aeropuerto José Martí International Airport Havana Cuba",
  "HBA": "Hobart Airport Cambridge Tasmania Tas Australia",
  "HDY": "Hat Yai International Airport Thailand",
  "HEL": "Helsinki-vantaan Lentoasema Helsinki Vantaa Finland",
  "HER": "Heraklion International Airport, Nikos Kazantzakis Crete Greece",
  "HFT": "Hammerfest Lufthavn Norway",
  "HGA": "Hargeisa Egal International Airport Somalia",
  "HGH": "Hangzhou Xiaoshan International Airport Zhejiang District China",
  "HGL": "Flughafen Helgoland-düne Heligoland Germany",
  "HHH": "Hilton Head Airport Island South Carolina Sc Usa",
  "HHN": "Flughafen Frankfurt-hahn Frankfurt–hahn Airport Kirchberg Rhineland-palatinate Germany",
  "HIR": "Honiara International Airport Guadalcanal Solomon Islands",
  "HKD": "Hakodate Airport Hokkaido Japan",
  "HKG": "Hong Kong International Airport Chek Lap Kok China",
  "HKT": "Phuket International Airport Thailand",
  "HLP": "Bandar Udara Halim Perdanakusuma Jakarta East Indonesia",
  "HMO": "Aeropuerto Internacional General Ignacio Pesqueira García International Airport Hermosillo Sonora So Mexico",
  "HND": "Tokyo International Airport Japan",
  "HNL": "Daniel K. Inouye International Airport Honolulu Oahu Hawaii Hi Usa",
  "HNM": "Hana Airport Hawaii Hi Usa",
  "HOB": "Lea County Regional Airport Hobbes New Mexico Nm Usa",
  "HOF": "Al-ahsa International Airport Hofuf Eastern Province Saudi Arabia",
  "HOG": "Frank País Airport Holguín Holguin Cuba",
  "HOR": "Aeroporto Internacional Da Horta Castelo Branco Azores Portugal",
  "HOT": "Memorial Field Airport Springs Arkansas Ar Usa",
  "HOU": "William P. Hobby Airport Houston Texas Tx Usa",
  "HOV": "Ørsta–volda Lufthavn, Hovden Ørsta Volda Norway",
  "HPH": "Sân Bay Quốc Tế Cát Bi Cat Hai Phong Vietnam",
  "HPN": "Westchester County Airport White Plains New York Ny Usa",
  "HQM": "Bowerman Airport Hoquiam Grays Harbor County Washington Wa Usa",
  "HRB": "Harbin Taiping International Airport China",
  "HRE": "Harare International Airport Zimbabwe",
  "HRG": "Hurghada International Airport Egypt",
  "HRI": "Mattala Rajapaksa International Airport Hambantota Sri Lanka",
  "HRL": "Valley International Airport Harlingen Texas Tx Usa",
  "HSV": "Huntsville International Airport Alabama Al Usa",
  "HUF": "Terre Haute International Airport Indiana In Usa",
  "HUH": "Huahine – Fare Airport French Polynesia France",
  "HUI": "Phu Bai International Airport Huế Vietnam",
  "HUU": "Aeropuerto Alférez Fap David Figueroa Fernandini Airport Huánuco Peru",
  "HUY": "Humberside Airport Kirmington North Lincolnshire Uk",
  "HVN": "Tweed-new Haven Regional Airport New Connecticut Ct Usa",
  "HYA": "Barnstable Municipal Airport Cape Cod Hyannis Massachusetts Ma Usa",
  "HYD": "Rajiv Gandhi International Airport Hyderabad Telangana Tg India",
  "HZG": "Hanzhong Chenggu Airport China",
  "IAD": "Dulles International Airport Washington D.c. Virginia Va Usa",
  "IAH": "George Bush Intercontinental Airport Houston Texas Tx Usa",
  "IAS": "Aeroportul Internațional Iași Iasi International Airport Romania",
  "IBZ": "Aeropuerto De Ibiza Formentera Spain",
  "ICN": "Incheon International Airport Seoul Jung District Korea South",
  "ICT": "Dwight D. Eisenhower National Airport Wichita Kansas Ks Usa",
  "IDA": "Idaho Falls Regional Airport Bonneville County Id Usa",
  "IDR": "Devi Ahilyabai Holkar Airport Indore Madhya Pradesh Mp India",
  "IEV": "Kyiv International Airport Kiev Zhuliany Ukraine",
  "IFP": "Laughlin/bullhead International Airport Bullhead City Nevada Arizona Az Usa",
  "IGU": "Aeroporto Internacional De Foz Do Iguaçu/cataratas Iguaçu Paraná Pr Brazil",
  "IGY": "Wright Brothers Field Jezero Crater Mars",
  "IIA": "Aeradróm Inis Meáin Inishmaan Ireland",
  "IKA": "Tehran Imam Khomeini International Airport Ahmadabad Iran",
  "IKT": "Irkutsk International Airport Russia",
  "ILD": "Aeroport Lleida-alguaire Lleida Alguaire Spain",
  "ILG": "Wilmington Airport Delaware De Usa",
  "IND": "Indianapolis International Airport Indiana In Usa",
  "INN": "Flughafen Innsbruck Austria",
  "INQ": "Aeradróm Inis Oírr Inisheer Ireland",
  "INU": "Nauru International Airport Yaren",
  "INV": "Port-adhair Inbhir Nis Inverness Dalcross Scotland Uk",
  "IOM": "Isle Of Man Airport Ronaldsway Uk",
  "IOR": "Aeradróm Inis Mór Inishmore Kilronan Ireland",
  "IPC": "Mataveri International Airport Easter Island Rapa Nui Chile",
  "IPH": "Sultan Azlan Shah Airport Ipoh Malaysia",
  "IPN": "Aeroporto Da Usiminas Airport Ipatinga Santana Do Paraíso Minas Gerais Mg Brazil",
  "IQQ": "Aeropuerto Internacional Diego Aracena International Airport Iquique Chile",
  "IQT": "Aeropuerto Internacional Coronel Fap Francisco Secada Vignetta Iquitos Peru",
  "ISB": "Benazir Bhutto International Airport Islamabad Rawalpindi Punjab Pb Pakistan",
  "ISC": "St Mary’s Airport Isles Of Scilly Cornwall England Uk",
  "ISL": "Istanbul Atatürk Havalimanı Yeşilköy Turkey",
  "ISP": "Long Island Macarthur Airport Islip New York Ny Usa",
  "IST": "Istanbul Airport Turkey",
  "ITM": "Osaka International Airport Itami Japan",
  "ITO": "Hilo International Airport Hawaii Hi Usa",
  "ITP": "Aeroporto Ernani Do Amaral Peixoto Itaperuna Airport Rio De Janeiro Rj Usa",
  "IWA": "Ivanovo Yuzhny Airport Russia",
  "IXA": "Agartala Airport Tripura Tr India",
  "IXB": "Bagdogra Airport Siliguri West Bengal Wb India",
  "IXC": "Chandigarh International Airport Ch India",
  "IXM": "Madurai Airport Tamil Nadu Tn India",
  "IXZ": "Veer Savarkar International Airport Port Blair Andaman And Nicobar Islands An India",
  "JAC": "Jackson Hole Airport Teton County Wyoming Wy Usa",
  "JAI": "Jaipur International Airport Rajasthan Rj India",
  "JAN": "Jackson–medgar Wiley Evers International Airport Jackson Mississippi Ms Usa",
  "JAU": "Aeropuerto Francisco Carlé Airport Jauja Junín Peru",
  "JAV": "Ilulissat Lufthavn Disko Bay Greenland Denmark",
  "JAX": "Jacksonville International Airport Florida Fl Usa",
  "JDF": "Aeroporto Francisco Álvares De Assis Airport Juiz Fora Serrinha Minas Gerais Mg Brazil",
  "JED": "King Abdulaziz International Airport Jeddah Saudi Arabia",
  "JER": "Jersey Airport Saint Peter Channel Islands",
  "JFK": "John F. Kennedy International Airport New York City Ny Usa",
  "JHM": "Kapalua Airport Lahaina Hawaii Hi Usa",
  "JIB": "Aéroport International De Djibouti–ambouli Djibouti City Ambouli",
  "JJG": "Aeroporto Regional Sul - Humberto Ghizzo Bortoluzzi Airport Jaguaruna Santa Catarina Sc Brazil",
  "JJN": "Quanzhou Jinjiang International Airport Fujian China",
  "JKH": "Chios Island National Airport North Aegean Greece",
  "JNB": "O. R. Tambo International Airport Johannesburg Kempton Park South Africa",
  "JOG": "Bandar Udara Internasional Adisucipto International Airport Yogyakarta Central Java Indonesia",
  "JOI": "Aeroporto De Joinville-lauro Carneiro Loyola Lauro Joinville Santa Catarina Sc Brazil",
  "JPA": "Aeroporto Internacional Presidente Castro Pinto International Airport João Pessoa Bayeux Paraíba Pb Brazil",
  "JRO": "Kilimanjaro International Airport Arusha Moshi Hai District Tanzania",
  "JSI": "Skiathos Airport, Alexandros Papadiamantis Thessaly Greece",
  "JUB": "Juba International Airport South Sudan",
  "JUL": "Aeropuerto Internacional Inca Manco Cápac International Airport Juliaca Puno Peru",
  "KAN": "Mallam Aminu Kano International Airport Nigeria",
  "KBL": "Hamid Karzai International Airport Kabul Afghanistan",
  "KBP": "Boryspil International Airport Kiev Ukraine",
  "KBR": "Lapangan Terbang Sultan Ismail Petra Airport Kota Bharu Kelantan Malaysia",
  "KBV": "Krabi International Airport Thailand",
  "KCH": "Kuching International Airport Malaysia",
  "KEF": "Keflavíkurflugvöllur Keflavík Reykjavík Iceland",
  "KER": "Kerman International Airport Iran",
  "KFZ": "Kukës International Airport Zayed-north Wings Albania",
  "KGL": "Kigali International Airport Rwanda",
  "KHH": "Kaohsiung International Airport Taiwan",
  "KHI": "Jinnah International Airport Karachi Sindh Sn Pakistan",
  "KIH": "Kish International Airport Island Iran",
  "KIN": "Norman Manley International Airport Kingston Jamaica",
  "KIR": "Kerry Airport Farranfore Ireland",
  "KIV": "Chișinău International Airport Chisinau Moldova",
  "KIX": "Kansai International Airport Osaka Japan",
  "KLO": "Kalibo International Airport Philippines",
  "KLU": "Airport Klagenfurt Austria",
  "KMG": "Kunming Changshui International Airport Guandu District China",
  "KNO": "Bandar Udara Internasional Kualanamu International Airport Medan Deli Serdang Indonesia",
  "KOA": "Kona International Airport Kailua-kona Kalaoa Hawaii Hi Usa",
  "KOE": "Bandar Udara Internasional El Tari International Airport Kupang Indonesia",
  "KOV": "Kokshetau Airport Kazakhstan",
  "KRK": "Kraków Airport Im. Jana Pawła Ii John Paul International Balice Poland",
  "KRN": "Kiruna Flygplats Norrbotten Sweden",
  "KRR": "Krasnodar International Airport Russia",
  "KRS": "Kristiansand Lufthavn, Kjevik Norway",
  "KRT": "Khartoum International Airport Sudan",
  "KSA": "Kosrae International Airport Micronesia",
  "KSC": "Medzinárodné Letisko Košice Kosice International Airport Barca Slovakia",
  "KSH": "Shahid Ashrafi Esfahani Airport Kermanshah Iran",
  "KSN": "Kostanay International Airport Kazakhstan",
  "KTI": "Techo International Airport Phnom Penh Kandal Stueng Cambodia",
  "KTM": "Tribhuvan International Airport Kathmandu Nepal",
  "KTT": "Kittilän Lentoasema Kittilä Finland",
  "KTW": "Międzynarodowy Port Lotniczy Katowice Pyrzowice Silesian Voivodeship Poland",
  "KUA": "Sultan Haji Ahmad Shah Airport Kuantan Malaysia",
  "KUH": "Kushiro Airport Hokkaido Japan",
  "KUL": "Lapangan Terbang Antarabangsa Kuala Lumpur Sepang Malaysia",
  "KUN": "Kauno Tarptautinis Oro Uostas Kaunas Lithuania",
  "KUO": "Kuopion Lentoasema Kuopio Siilinjärvi Finland",
  "KWE": "Guiyang Longdongbao International Airport Guizhou Province China",
  "KWI": "Kuwait International Airport City Farwaniya",
  "KZN": "Kazan International Airport Tatarstan Russia",
  "KZO": "Kyzylorda Airport Kazakhstan",
  "LAD": "Aeroporto Internacional 4 De Fevereiro Quatro International Airport Luanda Angola",
  "LAF": "Purdue University Airport Lafayette West Indiana In Usa",
  "LAN": "Capital Region International Airport Lansing Dewitt Township Michigan Mi Usa",
  "LAS": "Harry Reid International Airport Vegas Paradise Nevada Nv Usa",
  "LAX": "Los Angeles International Airport California Ca Usa",
  "LBA": "Leeds Bradford International Airport England Uk",
  "LBB": "Lubbock Preston Smith International Airport Texas Tx Usa",
  "LBC": "Flughafen Lübeck Lubeck Germany",
  "LBF": "North Platte Regional Airport Nebraska Ne Usa",
  "LBJ": "Bandar Udara Komodo Airport Labuan Bajo Flores Island Indonesia",
  "LBU": "Lapangan Terbang Labuan Malaysia",
  "LBV": "Aéroport De Libreville Au Gabon",
  "LCA": "Larnaca International Airport Cyprus",
  "LCG": "Aeroporto Da Coruña-alvedro A Coruña Galicia Spain",
  "LCH": "Lake Charles Regional Airport Louisiana La Usa",
  "LCK": "Rickenbacker International Airport Columbus Lockbourne Ohio Oh Usa",
  "LCY": "London City Airport Silvertown England Uk",
  "LDY": "City Of Derry Airport Eglinton Northern Ireland Uk",
  "LED": "Aeroport Pulkovo Saint Petersburg Russia",
  "LEI": "Aeropuerto De Almería Almeria Spain",
  "LEJ": "Flughafen Leipzig/halle Leipzig Halle Germany",
  "LEN": "Aeropuerto De León Leon Spain",
  "LEU": "Aeropuerto De La Seu D'urgell Andorra Spain",
  "LEX": "Blue Grass Airport Lexington Kentucky Ky Usa",
  "LFT": "Lafayette Regional Airport Louisiana La Usa",
  "LFW": "Lomé–tokoin Airport Lomé Togo",
  "LGA": "Laguardia Airport New York City Ny Usa",
  "LGB": "Long Beach Airport California Ca Usa",
  "LGG": "Liège Airport Liege Belgium",
  "LGK": "Lapangan Terbang Antarabangsa Langkawi Perlis Malaysia",
  "LGW": "Gatwick Airport London Crawley England Uk",
  "LHE": "Allama Iqbal International Airport Lahore Punjab Pb Pakistan",
  "LHR": "London Heathrow Airport England Uk",
  "LIH": "Lihue Airport Kauai Hawaii Hi Usa",
  "LIL": "Aéroport De Lille France",
  "LIM": "Aeropuerto Internacional Jorge Chávez International Airport Lima Callao Peru",
  "LIN": "Aeroporto Di Milano-linate Milan Linate Italy",
  "LIR": "Aeropuerto Internacional Daniel Oduber Quirós International Airport Liberia Costa Rica",
  "LIS": "Aeroporto Humberto Delgado Lisbon Portela Portugal",
  "LIT": "Bill And Hillary Clinton National Airport Little Rock Adams Field Arkansas Ar Usa",
  "LJU": "Letališče Jožeta Pučnika Ljubljana Zgornji Brnik Slovenia",
  "LKO": "Chaudhary Charan Singh International Airport Lucknow Utter Pradesh Up India",
  "LLW": "Lilongwe International Airport Malawi",
  "LMN": "Lapangan Terbang Limbang Sarawak Malaysia",
  "LMT": "Crater Lake - Klamath Regional Airport Falls Oregon Or Usa",
  "LNK": "Lincoln Airport Nebraska Ne Usa",
  "LNZ": "Linz Airport Austria",
  "LOP": "Lombok International Airport Mataram West Nusa Tenggara Ntb Indonesia",
  "LOS": "Murtala Muhammed International Airport Lagos Ikeja Nigeria",
  "LPA": "Aeropuerto De Gran Canaria Las Palmas Canary Islands Spain",
  "LPB": "Aeropuerto Internacional El Alto La Paz Bolivia",
  "LPL": "Liverpool John Lennon Airport Speke England Uk",
  "LPQ": "Luang Prabang International Airport Laos",
  "LRD": "Laredo International Airport Texas Tx Usa",
  "LRH": "Aéroport De La Rochelle – Ile Ré France",
  "LSE": "La Crosse Regional Airport Wisconsin Wi Usa",
  "LTN": "London Luton Airport England Uk",
  "LUK": "Cincinnati Municipal Airport Ohio Oh Usa",
  "LUN": "Kenneth Kaunda International Airport Lusaka Zambia",
  "LUX": "Aéroport De Luxembourg City Findel",
  "LVI": "Harry Mwanga Nkumbula International Airport Livingstone Victoria Falls Zambia",
  "LWB": "Greenbrier Valley Airport Lewisburg West Virginia Wv Usa",
  "LWO": "Lviv Danylo Halytskyi International Airport Ukraine",
  "LXR": "Luxor International Airport Egypt",
  "LYR": "Svalbard Lufthavn, Longyear Longyearbyen Norway",
  "LYS": "Aéroport Lyon-saint-exupéry Saint Exupéry Lyon Colombier-saugnieu France",
  "MAA": "Chennai International Airport Tirusulam Tamil Nadu Tn India",
  "MAD": "Aeropuerto Adolfo Suárez Madrid-barajas Madrid–barajas Airport Madrid Barajas Spain",
  "MAF": "Midland International Air And Space Port Odessa Texas Tx Usa",
  "MAH": "Aeropuerto De Menorca Mahón Spain",
  "MAJ": "Marshall Islands International Airport Majuro",
  "MAN": "Manchester Airport Ringway England Uk",
  "MAO": "Aeroporto Internacional Brigadeiro Eduardo Gomes International Airport Manaus Amazonas Am Brazil",
  "MBA": "Moi International Airport Mombasa Kenya",
  "MBJ": "Sangster International Airport Montego Bay Jamaica",
  "MBS": "International Airport Freeland Michigan Mi Usa",
  "MCE": "Merced Regional Airport California Ca Usa",
  "MCI": "Kansas City International Airport Missouri Mo Usa",
  "MCO": "Orlando International Airport Florida Fl Usa",
  "MCP": "Aeroporto Internacional De Macapá-alberto Alcolumbre Macapa International Airport Macapá Amapá Ap Brazil",
  "MCT": "Muscat International Airport Oman",
  "MCW": "Mason City Municipal Airport Iowa Ia Usa",
  "MCZ": "Aeroporto Internacional Maceió/zumbi Dos Palmares Zumbi Maceió Alagoas Al Brazil",
  "MDC": "Bandar Udara Internasional Sam Ratulangi Manado East Kalimantan Indonesia",
  "MDE": "Aeropuerto Internacional José María Córdova Medellín Rionegro Colombia",
  "MDL": "Mandalay International Airport Tada-u Myanmar",
  "MDQ": "Aeropuerto Internacional De Mar Del Plata “ástor Piazzolla” Astor Piazzolla Argentina",
  "MDT": "Harrisburg International Airport Middletown Pennsylvania Pa Usa",
  "MDW": "Midway International Airport Chicago Illinois Il Usa",
  "MDZ": "Aeropuerto Internacional Gobernador Francisco Gabrielli Governor Mendoza Argentina",
  "MED": "Prince Mohammad Bin Abdulaziz International Airport Medina Saudi Arabia",
  "MEL": "Melbourne Airport Tullamarine Victoria Vic Australia",
  "MEM": "Memphis International Airport Tennessee Tn Usa",
  "MEX": "Aeropuerto Internacional Benito Juárez International Airport Mexico City Distrito Federal Df",
  "MFD": "Mansfield Lahm Regional Airport Ohio Oh Usa",
  "MGA": "Aeropuerto Internacional Augusto C. Sandino César International Airport Managua Nicaragua",
  "MGL": "Flughafen Düsseldorf Mönchengladbach Dusseldorf Germany",
  "MGM": "Montgomery Regional Airport Alabama Al Usa",
  "MHD": "Shahid Hashemi Nejad Airport Mashhad Iran",
  "MHT": "Manchester–boston Regional Airport Manchester Boston New Hampshire Nh Usa",
  "MIA": "Miami International Airport Florida Fl Usa",
  "MJV": "Aeropuerto De Murcia-san Javier Murcia San Spain",
  "MKC": "Charles B. Wheeler Downtown Airport Kansas City Missouri Mo Usa",
  "MKE": "General Mitchell International Airport Milwaukee Wisconsin Wi Usa",
  "MKG": "Muskegon County Airport Norton Shores Michigan Mi Usa",
  "MLA": "Ajruport Internazzjonali Ta 'malta Valletta Luqa Malta",
  "MLB": "Melbourne International Airport Florida Fl Usa",
  "MLE": "Ibrahim Nasir International Airport Male Kaafu Atoll Maldives",
  "MLH": "Euroairport Basel–mulhouse–freiburg Mulhouse Saint-louis Switzerland France",
  "MLI": "Quad City International Airport Moline Illinois Il Usa",
  "MLN": "Aeropuerto De Melilla Spain",
  "MLU": "Monroe Regional Airport Louisiana La Usa",
  "MME": "Durham Tees Valley Airport Darlington Middlesbrough England Uk",
  "MMH": "Mammoth Yosemite Airport Lakes California Ca Usa",
  "MMK": "Murmansk Airport Murmashi Russia",
  "MMX": "Malmö Flygplats Svedala Sweden",
  "MNL": "Paliparang Pandaigdig Ng Ninoy Aquino Manila Pasay Philippines",
  "MOB": "Mobile Regional Airport Alabama Al Usa",
  "MOO": "Moomba Airport South Australia Sa",
  "MPM": "Maputo International Airport Mozambique",
  "MQC": "Aéroport De Miquelon Saint Pierre And France",
  "MQL": "Mildura Airport Victoria Vic Australia",
  "MRS": "Aéroport De Marseille Provence Marignane France",
  "MRU": "Sir Seewoosagur Ramgoolam International Airport Plaine Magnien Mauritius",
  "MRY": "Monterey Regional Airport California Ca Usa",
  "MSN": "Dane County Regional Airport Madison Wisconsin Wi Usa",
  "MSO": "Missoula International Airport Montana Mt Usa",
  "MSP": "Minneapolis–saint Paul International Airport Twin Cities St. Minnesota Mn Usa",
  "MSQ": "Minsk National Airport Kastrychnitski Belarus",
  "MST": "Maastricht Aachen Airport Beek Netherlands",
  "MSU": "Moshoeshoe I International Airport Maseru Mazenod Lesotho",
  "MSY": "Louis Armstrong International Airport New Orleans Louisiana La Usa",
  "MTJ": "Montrose Regional Airport Colorado Co Usa",
  "MTS": "Matsapha Airport Manzini Swaziland",
  "MTY": "Aeropuerto Internacional Mariano Escobedo Monterrey Apodaca Nuevo León Nl Mexico",
  "MUB": "Maun International Airport Botswana",
  "MUC": "Flughafen München Franz Josef Strauß Munich Freising Germany",
  "MUX": "Multan International Airport Punjab Pb Pakistan",
  "MVD": "Aeropuerto Internacional De Carrasco/general Cesáreo L. Berisso International Airport Montevideo Canelones Uruguay",
  "MVY": "Martha’s Vineyard Airport Massachusetts Ma Usa",
  "MXE": "Laurinburg–maxton Airport Maxton Rockingham North Carolina Nc Usa",
  "MXP": "Aeroporto Di Milano-malpensa Malpensa Milan Ferno Italy",
  "MYF": "Montgomery Field Airport San Diego California Ca Usa",
  "MYR": "Myrtle Beach International Airport South Carolina Sc Usa",
  "MYT": "Myitkyina Airport Myanmar",
  "MZL": "Aeropuerto La Nubia Manizales Colombia",
  "NAG": "Dr. Babasaheb Ambedkar International Airport Nagpur Maharashtra Mh India",
  "NAN": "Nadi International Airport Viti Levu Fiji",
  "NAP": "Aeroporto Internazionale Di Napoli Naples Italy",
  "NAS": "Lynden Pindling International Airport Nassau Bahamas",
  "NAT": "Aeroporto Internacional Augusto Severo Natal Parnamirim Rio Grande Do Norte Rn Brazil",
  "NBO": "Jomo Kenyatta International Airport Nairobi Embakasi Kenya",
  "NCE": "Aéroport Nice Côte D'azur France",
  "NCL": "Newcastle International Airport Woolsington England Uk",
  "NDJ": "N’djamena International Airport N'djamena Chad",
  "NDL": "N’délé Airport Central African Republic",
  "NDR": "Nador International Airport Morocco",
  "NER": "Chulman Neryungri Airport Russia",
  "NGB": "Ningbo Lishe International Airport Zhejiang China",
  "NGO": "Chūbu Centrair International Airport Nagoya Tokoname City Japan",
  "NGS": "Nagasaki Airport Ōmura Japan",
  "NIC": "Nicosia International Airport Cyprus",
  "NIM": "Diori Hamani International Airport Niamey Niger",
  "NKC": "Nouakchott International Airport Mauritania",
  "NKG": "Nanjing Lukou International Airport Jiangsu China",
  "NLA": "Simon Mwansa Kapwepwe International Airport Ndola Zambia",
  "NLK": "Norfolk Island Airport Australia",
  "NNG": "Nanning Wuxu International Airport Guangxi China",
  "NNR": "Aerfort Chonamara Inverin Connemara Ireland",
  "NOC": "Ireland West Airport Knock Charlestown",
  "NOS": "Fascene Airport Nosy Be Madagascar",
  "NQY": "Newquay Cornwall Airport England Uk",
  "NQZ": "Nursultan Nazarbayev International Airport Astana Kazakhstan",
  "NRN": "Flughafen Weeze North Rhine-westphalia Germany",
  "NRT": "Narita International Airport Tokyo Japan",
  "NSK": "Alykel Airport Norilsk Krasnoyarsk Krai Russia",
  "NSN": "Nelson Airport Annesbrook New Zealand",
  "NTE": "Aéroport Nantes Atlantique Bouguenais France",
  "NTL": "Newcastle Airport Williamtown New South Wales Nsw Australia",
  "NUE": "Flughafen Nürnberg Nuremberg Bavaria Germany",
  "NWI": "Norwich International Airport Norfolk England Uk",
  "NYO": "Stockholm Skavsta Flygplats Nyköping Sweden",
  "NZC": "Maria Reiche Neuman Airport Nazca Ica Peru",
  "OAK": "Oakland International Airport California Ca Usa",
  "OBN": "Oban Airport North Connel Scotland Uk",
  "ODS": "Odessa International Airport Ukraine",
  "OGG": "Kahului Airport Maui Hawaii Hi Usa",
  "OGS": "Ogdensburg International Airport Ottawa New York Ny Usa",
  "OHD": "Aerodrom Ohrid “sv. Apostol Pavle” Saint Paul The Apostle Orovnik Macedonia",
  "ORH": "Worcester Regional Airport Massachusetts Ma Usa",
  "OKA": "Naha Airport Okinawa Japan",
  "OKC": "Will Rogers World Airport Oklahoma City Ok Usa",
  "OMA": "Eppley Airfield Omaha Nebraska Ne Usa",
  "OME": "Nome Airport Alaska Ak Usa",
  "OMO": "Mostar International Airport Ortiješ Bosnia And Herzegovina",
  "OMS": "Omsk Tsentralny Airport Siberia Russia",
  "ONT": "La/ontario International Airport Ontario California Ca Usa",
  "OOL": "Gold Coast Airport Coolangatta Bilinga Queensland Qld Australia",
  "OPO": "Aeroporto Francisco Sá Carneiro De Airport Porto Oporto Portugal",
  "ORB": "Örebro Flygplats Orebro Sweden",
  "ORD": "O’hare International Airport Chicago Illinois Il Usa",
  "ORF": "Norfolk International Airport Virginia Va Usa",
  "ORK": "Cork Airport Ballygarvan Ireland",
  "ORY": "Aéroport De Paris-orly Paris Orly France",
  "OSH": "Wittman Regional Airport Oshkosh Wisconsin Wi Usa",
  "OSL": "Oslo Lufthavn Gardermoen Norway",
  "OST": "Internationale Luchthaven Oostende-brugge Ostend Bruges Belgium",
  "OSU": "Ohio State University Airport Columbus Oh Usa",
  "OTP": "Aeroportul Internațional Henri Coandă Bucharest Otopeni Romania",
  "OTZ": "Ralph Wien Memorial Airport Kotzebue Alaska Ak Usa",
  "OUA": "Ouagadougou International Airport Burkina Faso",
  "OUD": "Oujda Angads Airport Morocco",
  "OUL": "Oulun Lentoasema Oulu Finland",
  "OVB": "Novosibirsk Tolmachevo Airport Russia",
  "OVD": "Aeropuerto De Asturias Oviedo Spain",
  "OWD": "Norwood Memorial Airport Massachusetts Ma Usa",
  "OXB": "Aeroporto Internacional Osvaldo Vieira International Airport Bissau Guinea-bissau",
  "OXF": "London Oxford Airport Kidlington England Uk",
  "PAE": "Snohomish County Airport Everett Mukilteo Washington Wa Usa",
  "PAP": "Aéroport International Toussaint L'ouverture Airport Port-au-prince Tabarre Haiti",
  "PAS": "Paros National Airport Greece",
  "PBG": "Plattsburgh International Airport New York Ny Usa",
  "PBH": "Paro International Airport Bhutan",
  "PBI": "Palm Beach International Airport Miami Florida Fl Usa",
  "PBM": "Johan Adolf Pengel International Airport Paramaribo Zanderij Suriname",
  "PCL": "Aeropuerto Internacional Capitán Fap David Abensur Rengifo Pucallpa Ucayalí Peru",
  "PDG": "Bandar Udara Internasional Minangkabau International Airport Padang West Sumatra Indonesia",
  "PDK": "Dekalb–peachtree Airport Chamblee Atlanta Georgia Ga Usa",
  "PDL": "Aeroporto João Paulo Ii John Paul Airport Ponta Delgada São Miguel Azores Portugal",
  "PDP": "Aeropuerto Internacional Capitán De Corbeta Carlos A. Curbelo Punta Del Este Piriápolis Uruguay",
  "PDV": "Letishte Plovdiv Krumovo Bulgaria",
  "PDX": "Portland International Airport Oregon Or Usa",
  "PEE": "Perm International Airport Russia",
  "PEI": "Aeropuerto Internacional Matecaña Matecana International Airport Pereira Colombia",
  "PEK": "Beijing Capital International Airport Chaoyang District China",
  "PEM": "Aeropuerto Internacional Padre Aldamiz International Airport Puerto Maldonado Madre De Dios Peru",
  "PEN": "Lapangan Terbang Antarabangsa Pulau Pinang Penang International Airport Bayan Lepas Malaysia",
  "PER": "Perth Airport Western Australia Wa",
  "PET": "Aeroporto Internacional João Simões Lopes Neto International Airport Pelotas Rio Grande Do Sul Rs Brazil",
  "PEW": "Bacha Khan International Airport Peshawar Khyber Pakhtunkhwa Kpk Pakistan",
  "PFB": "Aeroporto Lauro Kurtz Airport Passo Fundo Rio Grande Do Sul Rs Brazil",
  "PFO": "Paphos International Airport Cyprus",
  "PHC": "Port Harcourt International Airport Omagwa Nigeria",
  "PHF": "Newport News/williamsburg International Airport News Williamsburg Virginia Va Usa",
  "PHK": "Palm Beach County Glades Airport Pahokee Florida Fl Usa",
  "PHL": "Philadelphia International Airport Pennsylvania Pa Usa",
  "PHX": "Sky Harbor International Airport Phoenix Arizona Az Usa",
  "PIE": "St. Pete–clearwater International Airport Clearwater Pinellas County Florida Fl Usa",
  "PIK": "Glasgow Prestwick Airport Scotland Uk",
  "PIO": "Aeropuerto Capitán Fap Renán Elías Olivera Pisco Ica Peru",
  "PIT": "Pittsburgh International Airport Pennsylvania Pa Usa",
  "PIU": "Aeropuerto Internacional Capitán Fap Guillermo Concha Iberico International Airport Piura Peru",
  "PIX": "Aeroporto Do Pico Madalena Azores Portugal",
  "PKU": "Sultan Syarif Kasim Ii International Airport Pekanbaru Indonesia",
  "PKX": "Beijing Daxing International Airport Chaoyang District China",
  "PLM": "Sultan Mahmud Badaruddin Ii International Airport Palembang Indonesia",
  "PLQ": "Tarptautinis Palangos Oro Uostas Palanga Klaipėda Lithuania",
  "PLS": "Providenciales International Airport Caicos Islands Uk",
  "PLU": "Aeroporto Carlos Drummond De Andrade Airport Belo Horizonte Pampulha Minas Gerais Mg Brazil",
  "PLZ": "Chief Dawid Stuurman International Airport Gqeberha Port Elizabeth South Africa",
  "PMI": "Aeropuerto De Palma Mallorca Spain",
  "PMO": "Aeroporto Falcone Borsellino Airport Palermo Sicily Italy",
  "PMW": "Aeroporto De Palmas-brigadeiro Lysias Rodrigues Palmas Tocantins To Brazil",
  "PNA": "Aeropuerto De Pamplona Spain",
  "PNH": "Phnom Penh International Airport Cambodia",
  "PNI": "Pohnpei International Airport Island Micronesia",
  "PNK": "Bandar Udara Internasional Supadio International Airport Pontianak West Kalimantan Indonesia",
  "PNQ": "Pune Airport Poona Maharashtra Mh India",
  "PNS": "Pensacola International Airport Florida Fl Usa",
  "PNT": "Aeródromo Teniente Julio Gallardo Airport Puerto Natales Chile",
  "PNY": "Puducherry Airport Pondicherry India",
  "PNZ": "Aeroporto De Petrolina–senador Nilo Coelho Petrolina Juazeiro Pernambuco Pe Brazil",
  "POA": "Aeroporto Internacional Salgado Filho International Airport Porto Alegre São João Rio Grande Do Sul Rs Brazil",
  "POM": "Jacksons International Airport Port Moresby Papua New Guinea",
  "POO": "Aeroporto Poços De Caldas Pocos Minas Gerais Mg Brazil",
  "POP": "Aeropuerto Internacional Gregorio Luperón International Airport Puerto Plata Dominican Republic",
  "POS": "Piarco International Airport Port Of Spain Trinidad And Tobago",
  "POZ": "Port Lotniczy Poznań–ławica Im. Henryka Wieniawskiego Henryk Wieniawski Airport Poznań Poland",
  "PPG": "Pago International Airport Tafuna American Samoa Usa",
  "PPT": "Fa'a'ā International Airport Tahiti Pape'ete French Polynesia France",
  "PQC": "Sân Bay Quốc Tế Phú Quôc Phu Quoc Vietnam",
  "PRG": "Letiště Václava Havla Praha Vaclav Havel Airport Prague Ruzyně Czech Republic",
  "PRN": "Pristina International Airport Adem Jashari Kosovo",
  "PSA": "Aeroporto Internazionale Di Pisa Italy",
  "PSC": "Tri-cities Airport Pasco Washington Wa Usa",
  "PSE": "Aeropuerto Mercedita Airport Ponce Puerto Rico Usa",
  "PSM": "Portsmouth International Airport At Pease New Hampshire Nh Usa",
  "PSP": "Palm Springs International Airport California Ca Usa",
  "PTK": "Oakland County International Airport Waterford Township Michigan Mi Usa",
  "PTP": "Aérodrome De Pointe-à-pitre Le Raizet Grande-terre Guadeloupe France",
  "PTY": "Aeropuerto Internacional De Tocumen International Airport Panama City",
  "PUB": "Pueblo Memorial Airport Colorado Co Usa",
  "PUF": "Aéroport Pau Pyrénées Airport Uzein France",
  "PUQ": "Aeropuerto Internacional Presidente Carlos Ibáñez Punta Arenas Chile",
  "PUS": "Gimhae International Airport Busan Pusan Korea South",
  "PVD": "Theodore Francis Green Memorial State Airport Providence Warwick Rhode Island Ri Usa",
  "PVG": "Shanghai Pudong International Airport China",
  "PVR": "Aeropuerto Internacional Lic. Gustavo Díaz Ordaz International Airport Puerto Vallarta Jalisco Ja Mexico",
  "PVU": "Provo Municipal Airport Utah Ut Usa",
  "PWK": "Chicago Executive Airport Wheeling Prospect Heights Illinois Il Usa",
  "PWM": "Portland International Jetport Westbrook Maine Me Usa",
  "PXO": "Aeroporto De Porto Santo Madeira Portugal",
  "PXU": "Sân Bay Pleiku Vietnam",
  "PZO": "Manuel Carlos Piar Guayana International Airport Ciudad Puerto Ordaz Bolívar Venezuela",
  "QBS": "Aeroporto Di Verona-boscomantico Airport Verona Italy",
  "QRO": "Aeropuerto Intercontinental De Querétaro Qe Mexico",
  "RAI": "Aeroporto Internacional Nelson Mandela International Airport Praia Santiago Island Cape Verde",
  "RAK": "Marrakesh Menara Airport Morocco",
  "RAO": "Aeroporto Estadual De Ribeirão Preto - Doutor Leite Lopes State Airport Dr. Ribeirao São Paulo Sp Brazil",
  "RAR": "Papa Rererangi O Rarotonga International Airport Avarua Cook Islands",
  "RBA": "Rabat–salé Airport Rabat Salé Morocco",
  "RBD": "Dallas Executive Airport Texas Tx Usa",
  "RBO": "Aeropuerto Roboré Airport Bolivia",
  "RDD": "Redding Municipal Airport California Ca Usa",
  "RDU": "Raleigh–durham International Airport Raleigh Durham North Carolina Nc Usa",
  "REC": "Aeroporto Internacional Do Recife/guararapes–gilberto Freyre Recife Pernambuco Pe Brazil",
  "REP": "Siem Reap International Airport Cambodia",
  "RFD": "Chicago Rockford International Airport Illinois Il Usa",
  "RGI": "Rangiroa Airport French Polynesia France",
  "RGN": "Yangon International Airport Rangoon Myanmar",
  "RHO": "Rhodes International Airport “diagoras” Greece",
  "RIC": "Richmond International Airport Sandston Virginia Va Usa",
  "RIV": "March Air Reserve Base Riverside California Ca Usa",
  "RIW": "Riverton Regional Airport Wyoming Wy Usa",
  "RIX": "Starptautiskā Lidosta “rīga” Riga Latvia",
  "RJL": "Aeropuerto De Logroño-agoncillo Logroño Agoncillo Spain",
  "RKV": "Reykjavík Airport Iceland",
  "RLG": "Flughafen Rostock–laage Rostock Laage Germany",
  "RMI": "Aeroporto Internazionale Federico Fellini International Airport Rimini San Marino Italy",
  "RMS": "Ramstein Air Base Ramstein-miesenbach Kaiserslautern Germany",
  "RNO": "Reno–tahoe International Airport Reno Tahoe Nevada Nv Usa",
  "RNS": "Aéroport De Rennes - Saint-jacques France",
  "RNT": "Renton Municipal Airport Washington Wa Usa",
  "ROA": "Roanoke–blacksburg Regional Airport Roanoke Virginia Va Usa",
  "ROB": "Roberts International Airport Monrovia Liberia",
  "ROC": "Frederick Douglass Greater Rochester International Airport New York Ny Usa",
  "ROR": "Roman Tmetuchl International Airport Melekeok Airai Palau",
  "ROS": "Aeropuerto Internacional Rosario Islas Malvinas Funes Santa Fe Argentina",
  "ROV": "Aeroport Rostov-na-donu Rostov-on-don Russia",
  "ROW": "Roswell International Air Center New Mexico Nm Usa",
  "RPR": "Swami Vivekananda International Airport Raipur Mana Chhattisgarh Ct India",
  "RRG": "Sir Gaëtan Duval Airport Plaine Corail Rodrigues Mauritius",
  "RST": "Rochester International Airport Minnesota Mn Usa",
  "RSW": "Southwest Florida International Airport Fort Myers Fl Usa",
  "RTM": "Rotterdam The Hague Airport Netherlands",
  "RUH": "King Khalid International Airport Riyadh Saudi Arabia",
  "RUN": "Aéroport De La Réunion Roland Garros Saint-denis France",
  "RVN": "Rovaniemen Lentoasema Rovaniemi Finland",
  "RYG": "Moss Lufthavn, Rygge Norway",
  "RYK": "Shaikh Zayed International Airport Rahim Yar Khan Punjab Pb Pakistan",
  "RZE": "Port Lotniczy Rzeszów-jasionka Rzeszów Jasionka Poland",
  "SAB": "Juancho E. Yrausquin Airport Saba Netherlands",
  "SAF": "Santa Fe Municipal Airport New Mexico Nm Usa",
  "SAH": "Sana'a International Airport Yemen",
  "SAL": "Aeropuerto Internacional Monseñor Óscar Arnulfo Romero International Airport San Salvador La Paz El",
  "SAN": "Lindbergh Field Diego California Ca Usa",
  "SAT": "San Antonio International Airport Texas Tx Usa",
  "SAV": "Savannah/hilton Head International Airport Savannah Hilton Island Georgia Ga Usa",
  "SAW": "Sabiha Gökçen Uluslararası Havalimanı Istanbul Turkey",
  "SBA": "Santa Barbara Municipal Airport California Ca Usa",
  "SBD": "San Bernardino International Airport California Ca Usa",
  "SBN": "South Bend International Airport Indiana In Usa",
  "SBP": "San Luis Obispo County Regional Airport California Ca Usa",
  "SCE": "University Park Airport State College Bellefonte Pennsylvania Pa Usa",
  "SCK": "Stockton Metropolitan Airport California Ca Usa",
  "SCL": "Aeropuerto Internacional Comodoro Arturo Merino Benítez International Airport Santiago Pudahuel Chile",
  "SCO": "International Airport Aktau Kazakhstan",
  "SCQ": "Aeroporto Internacional De Santiago Compostela Galicia Spain",
  "SCT": "Socotra Airport Hadibu Yemen",
  "SDF": "Louisville Muhammad Ali International Airport Kentucky Ky Usa",
  "SDQ": "Aeropuerto Internacional Las Américas International Airport Santo Domingo Punta Caucedo Dominican Republic",
  "SDR": "Aeropuerto Seve Ballesteros - Santander Airport Maliaño Spain",
  "SDU": "Aeroporto Santos Dumont Airport Rio De Janeiro Rj Brazil",
  "SEA": "Seattle–tacoma International Airport Seattle Tacoma Washington Wa Usa",
  "SEN": "London Southend Airport England Uk",
  "SEX": "Sembach Kaserne Germany",
  "SFA": "Aéroport International De Sfax-thyna Sfax Thyna Tunisia",
  "SFJ": "Søndre Strømfjord Lufthavn Kangerlussuaq Qeqqata Greenland Denmark",
  "SFN": "Aeropuerto De Santa Fe - Sauce Viejo Airport Argentina",
  "SFO": "San Francisco International Airport California Ca Usa",
  "SGC": "Surgut International Airport Russia",
  "SGF": "Springfield–branson National Airport Springfield Missouri Mo Usa",
  "SGN": "Sân Bay Quốc Tế Tân Sơn Nhất Ho Chi Minh City Saigon Vietnam",
  "SGU": "St. George Regional Airport Utah Ut Usa",
  "SGY": "Skagway Airport Alaska Ak Usa",
  "SHA": "Shanghai Hongqiao International Airport China",
  "SHD": "Shenandoah Valley Regional Airport Staunton Weyers Cave Virginia Va Usa",
  "SHE": "Shenyang Taoxian International Airport Liaoning China",
  "SHV": "Shreveport Regional Airport Louisiana La Usa",
  "SID": "Aeroporto Internacional Amílcar Cabral International Airport Espargos Sal Island Cape Verde",
  "SIN": "Singapore Changi Airport",
  "SIP": "Simferopol International Airport Russia",
  "SIR": "Aéroport De Sion Rhone Valley Switzerland",
  "SJC": "Norman Y. Mineta San Jose International Airport California Ca Usa",
  "SJD": "Aeropuerto Internacional De Los Cabos International Airport San José Del Cabo Lucas Baja California Sur Bs Mexico",
  "SJJ": "Sarajevo International Airport Butmir Bosnia And Herzegovina",
  "SJK": "Aeroporto De São José Dos Campos-professor Urbano Ernesto Stumpf Airport Campos Sao Paulo Sp Brazil",
  "SJO": "Aeropuerto Internacional Juan Santamaría San José Alajuela Costa Rica",
  "SJU": "Aeropuerto Internacional Luis Muñoz Marín San Juan Carolina Puerto Rico Usa",
  "SJZ": "Aérodromo De São Jorge Velas Azores Portugal",
  "SKB": "Robert L. Bradshaw International Airport Basseterre Saint Kitts And Nevis",
  "SKG": "Thessaloniki International Airport, Macedonia Mikra Greece",
  "SKP": "Aerodrom Skopje Petrovec Macedonia",
  "SKT": "Sialkot International Airport Punjab Pakistan",
  "SKZ": "Sukkur Airport Sindh Sn Pakistan",
  "SLC": "Salt Lake City International Airport Utah Ut Usa",
  "SLE": "Salem Municipal Airport - Mcnary Field Oregon Or Usa",
  "SLK": "Adirondack Regional Airport Saranac Lake Placid New York Ny Usa",
  "SLM": "Aeropuerto De Salamanca-matacán Salamanca Matacán Castile And León Spain",
  "SLN": "Salina Regional Airport Kansas Ks Usa",
  "SLU": "George F. L. Charles Airport Castries Saint Lucia",
  "SLZ": "Aeroporto Internacional Marechal Cunha Machado International Airport São Luís Maranhão Ma Brazil",
  "SMA": "Aeroporto De Santa Maria Vila Do Porto Azores Portugal",
  "SMF": "Sacramento International Airport California Ca Usa",
  "SMI": "Samos International Airport, Aristarchos Of Island Greece",
  "SNA": "John Wayne International Airport Orange County Santa Ana California Ca Usa",
  "SNN": "Shannon Airport Ireland",
  "SNR": "Aéroport De Saint-nazaire - Montoir Airport France",
  "SOB": "Hévíz-balaton Repülőtér Heviz-balaton Airport Balaton Sarmellek Hungary",
  "SOC": "Bandar Udara Internasional Adisumarmo International Airport Surakarta Ngemplak Indonesia",
  "SOF": "Letishte Sofiya Sofia Vrazhdebna Bulgaria",
  "SOQ": "Bandar Udara Domine Edward Osok Airport Sorong West Papua Indonesia",
  "SOU": "Southampton Airport Eastleigh England Uk",
  "SOY": "Stronsay Airport Orkney Islands Scotland Uk",
  "SPC": "Aeropuerto De La Palma Airport Canary Islands Spain",
  "SPG": "Albert Whitted Airport Saint Petersburg Tampa Bay Florida Fl Usa",
  "SPN": "Saipan International Airport Northern Mariana Islands Usa",
  "SPU": "Zračna Luka Split Kastela Croatia",
  "SQL": "San Carlos Airport California Ca Usa",
  "SRE": "Aeropuerto Internacional Juana Azurduy De Padilla International Airport Sucre Bolivia",
  "SRG": "Bandar Udara Internasional Ahmad Yani Semarang East Java Indonesia",
  "SRQ": "Sarasota–bradenton International Airport Sarasota Bradenton Florida Fl Usa",
  "SSA": "Aeroporto Internacional De Salvador-deputado Luís Eduardo Magalhães Deputado Salvador Bahia Ba Brazil",
  "SSF": "Stinson Municipal Airport San Antonio Texas Tx Usa",
  "SSG": "Aeropuerto De Malabo Bioko Equatorial Guinea",
  "SSH": "Sharm El-sheikh International Airport Egypt",
  "STI": "Aeropuerto Internacional Del Cibao Santiago De Los Caballeros Dominican Republic",
  "STL": "Lambert–st. Louis International Airport St. Missouri Mo Usa",
  "STM": "Aeroporto De Santarém–maestro Wilson Fonseca Santarem-maestro Airport Santarém Pará Pa Brazil",
  "STN": "London Stansted Airport Mountfitchet England Uk",
  "STP": "St. Paul Downtown Airport Saint Twin Cities Minnesota Mn Usa",
  "STR": "Flughafen Stuttgart - Manfred Rommel Germany",
  "STS": "Charles M. Schulz - Sonoma County Airport Santa Rosa California Ca Usa",
  "STT": "Cyril E. King Airport Saint Thomas St. Virgin Islands Usa",
  "STX": "Henry E. Rohlsen Airport Saint Croix St. Virgin Islands Usa",
  "SUB": "Bandar Udara Internasional Juanda International Airport Surabaya Sidoarjo East Java Indonesia",
  "SUN": "Friedman Memorial Airport Hailey Valley Idaho Id Usa",
  "SUV": "Nausori International Airport Suva Viti Levu Fiji",
  "SUX": "Sioux Gateway Airport City Iowa Ia Usa",
  "SVD": "E. T. Joshua Airport Kingstown Arnos Vale Saint Vincent And The Grenadines",
  "SVG": "Stavanger Lufthavn, Sola Norway",
  "SVO": "Sheremetyevo International Airport Moscow Khimki Russia",
  "SVQ": "Aeropuerto De Sevilla Seville Spain",
  "SVX": "Koltsovo International Airport Yekaterinburg Sverdlovsk Russia",
  "SWF": "Stewart International Airport Newburgh Hudson Valley New York Ny Usa",
  "SXB": "Aéroport International De Strasbourg Entzheim France",
  "SXF": "Flughafen Berlin-schönefeld Berlin Schönefeld Germany",
  "SXL": "Sligo Airport Strandhill Ireland",
  "SXM": "Princess Juliana International Airport Simpson Bay Sint Maarten Saint Martin Netherlands",
  "SXR": "Srinagar International Airport Jammu And Kashmir Jk India",
  "SYD": "Sydney (kingsford Smith) Airport New South Wales Nsw Australia",
  "SYR": "Syracuse Hancock International Airport New York Ny Usa",
  "SYX": "Sanya Phoenix International Airport Hainan China",
  "SYZ": "Shiraz International Airport Iran",
  "SZB": "Lapangan Terbang Sultan Abdul Aziz Shah Airport Subang Kuala Lumpur Selangor Malaysia",
  "SZG": "Salzburg Airport W. A. Mozart Austria",
  "SZX": "Shenzhen Bao'an International Airport Guangdong China",
  "TAB": "A.n.r. Robinson International Airport Scarborough Crown Point Trinidad And Tobago",
  "TAK": "Takamatsu Airport Japan",
  "TAO": "Qingdao Liuting International Airport Shandong Chengyang District China",
  "TAS": "Toshkent Xalqaro Aeroporti Tashkent Uzbekistan",
  "TBB": "Sân Bay Đông Tác Dong Tac Airport Tuy Hoa Vietnam",
  "TBP": "Aeropuerto Capitán Fap Pedro Canga Rodríguez Airport Tumbes Peru",
  "TBS": "Tbilisi International Airport Georgia",
  "TBZ": "Tabriz International Airport Iran",
  "TCQ": "Aeropuerto Internacional Coronel Fap Carlos Ciriani Santa Rosa International Airport Tacna Peru",
  "TER": "Base Aérea Das Lajes Field Terceira Azores Portugal",
  "TEX": "Telluride Regional Airport Colorado Co Usa",
  "TFN": "Aeropuerto De Tenerife Norte Santa Cruz Canary Islands Spain",
  "TFS": "Aeropuerto De Tenerife Sur Reina Sofía Playa Las Américas Canary Islands Spain",
  "TGD": "Podgorica Airport Golubovci Montenegro",
  "TGI": "Aeropuerto Tingo María Huánuco Peru",
  "TGM": "Aeroportul Transilvania Târgu Mureș Airport Vidrasău Romania",
  "TGU": "Aeropuerto Internacional Toncontín International Airport Tegucigalpa Honduras",
  "THE": "Aeroporto De Teresina–senador Petrônio Portella Teresina Airport Piauí Pi Brazil",
  "THR": "Mehrabad International Airport Tehran Iran",
  "TIA": "Tirana International Airport Nënë Tereza Rinas Albania",
  "TIF": "Ta'if Regional Airport Mecca Province Saudi Arabia",
  "TIJ": "Aeropuerto Internacional De Tijuana Baja California Mexico",
  "TIP": "Tripoli International Airport Qasr Bin Ghashir Libya",
  "TIV": "Aerodrom Tivat Airport Montenegro",
  "TJM": "Roshchino International Airport Tyumen Russia",
  "TKK": "Chuuk International Airport Weno Truk Micronesia",
  "TLL": "Lennart Meri Tallinna Lennujaam Tallinn Estonia",
  "TLS": "Aéroport De Toulouse–blagnac Toulouse Blagnac France",
  "TLV": "Ben Gurion Airport Tel Aviv Israel",
  "TMC": "Bandar Udara Tambolaka Airport Indonesia",
  "TMS": "Aeroporto Internacional De São Tomé Sao Tome And Príncipe",
  "TNA": "Jinan Yaoqiang International Airport Shandong China",
  "TNG": "Tangier Ibn Battouta Airport Morocco",
  "TNM": "Aeropuerto Teniente Rodolfo Marsh Airport King George Island Villa Las Estrellas Antarctica",
  "TNR": "Ivato International Airport Antananarivo Madagascar",
  "TNT": "Dade-collier Training And Transition Airport Miami Fort Lauderdale Florida Fl Usa",
  "TOL": "Toledo Express Airport Ohio Oh Usa",
  "TOS": "Tromsø Lufthavn, Langnes Langes Norway",
  "TPA": "Tampa International Airport Florida Fl Usa",
  "TPE": "Taiwan Taoyuan International Airport Taipei City",
  "TPP": "Aeropuerto Cadete Fap Guillermo Del Castillo Paredes Airport Tarapoto San Martín Peru",
  "TRD": "Trondheim Lufthavn, Værnes Norway",
  "TRE": "Port-adhair Thirioah Tiree Balemartine Scotland Uk",
  "TRF": "Sandefjord Lufthavn, Torp Norway",
  "TRI": "Tri-cities Regional Airport Blountville Bristol Tennessee Tn Usa",
  "TRN": "Aeroporto Di Torino Sandro Pertini Turin Italy",
  "TRS": "Aeroporto Di Trieste–friuli Venezia Giulia Trieste Ronchi Dei Legionari Italy",
  "TRU": "Aeropuerto Internacional Capitán Fap Carlos Martínez De Pinillos International Airport Trujillo La Libertad Peru",
  "TRV": "Trivandrum International Airport Thiruvananthapuram Kerala Kl India",
  "TRW": "Bonriki International Airport South Tarawa Kiribati",
  "TSA": "Taipei Songshan Airport District Taiwan",
  "TSN": "Tianjin Binhai International Airport China",
  "TSR": "Aeroportul Internațional „traian Vuia” Timișoara Romania",
  "TTN": "Trenton–mercer Airport Trenton Ewing Township New Jersey Nj Usa",
  "TUL": "Tulsa International Airport Oklahoma Ok Usa",
  "TUN": "Tunis–carthage International Airport Tunis Carthage Tunisia",
  "TUS": "Tucson International Airport Arizona Az Usa",
  "TVC": "Cherry Capital Airport Traverse City Michigan Mi Usa",
  "TXL": "Flughafen Berlin-tegel “otto Lilienthal” Berlin Tegel Germany",
  "TYL": "Aeropuerto Capitán Fap Víctor Montes Arias Talara Piura Peru",
  "TYS": "Mcghee Tyson Airport Knoxville Alcoa Tennessee Tn Usa",
  "TZL": "Tuzla International Airport Zivinice Bosnia And Herzegovina",
  "UFA": "International Airport Bashkortostan Russia",
  "UIH": "Sân Bay Phù Cát Phu Cat Airport Qui Nhon Vietnam",
  "UIO": "Aeropuerto Internacional Mariscal Sucre International Airport Quito Tababela Pichincha Ecuador",
  "UKK": "Oskemen International Airport Ust-kamenogorsk Kazakhstan",
  "ULN": "Chinggis Khaan International Airport Ulaanbaatar Mongolia",
  "UPG": "Bandar Udara Internasional Sultan Hasanuddin Makassar South Sulawesi Indonesia",
  "URA": "Oral Ak Zhol Airport Uralsk Kazakhstan",
  "USH": "Aeropuerto Internacional De Ushuaia Malvinas Argentinas Argentina",
  "USM": "Samui International Airport Ko Thailand",
  "UTH": "Udon Thani International Airport Thailand",
  "UUD": "Baikal International Airport Ulan-ude Russia",
  "UUS": "Yuzhno-sakhalinsk Airport Russia",
  "UVF": "Hewanorra International Airport Vieux Fort Saint Lucia",
  "VAM": "Villa International Airport Maamigili Alif Dhaal Atoll Maldives",
  "VAR": "Letishte Varna Aksakovo Bulgaria",
  "VAV": "Vava’u International Airport Vava'u Tonga",
  "VCA": "Sân Bay Quốc Tế Cần Thơ Can Tho Vietnam",
  "VCE": "Aeroporto Di Venezia Marco Polo Venice Tessera Italy",
  "VCL": "Sân Bay Chu Lai Airport Tam Ky Vietnam",
  "VCP": "Aeroporto Internacional De Viracopos/campinas Viracopos International Airport Campinas São Paulo Sp Brazil",
  "VCS": "Sân Bay Côn Đảo Con Dao Son Island Vietnam",
  "VCV": "Southern California Logistics Airport Victorville Ca Usa",
  "VDE": "Aeropuerto De El Hierro Valverde Canary Islands Spain",
  "VDH": "Sân Bay Đồng Hới Dong Hoi Vietnam",
  "VER": "Aeropuerto Internacional De Veracruz International Airport Ve Mexico",
  "VGO": "Aeropuerto De Vigo Peinador Spain",
  "VGT": "North Las Vegas Airport Nevada Nv Usa",
  "VIE": "Flughafen Wien-schwechat Vienna Schwechat Austria",
  "VII": "Sân Bay Vinh Vietnam",
  "VIX": "Aeroporto De Vitória-eurico Aguiar Salles Vitória Espírito Santo Es Brazil",
  "VKG": "Sân Bay Rạch Giá Rach Gia Vietnam",
  "VKO": "Vnukovo International Airport Moscow Russia",
  "VLC": "Aeropuerto De Valencia Manises Spain",
  "VLI": "Bauerfield International Airport Port Vila Vanuatu",
  "VLL": "Aeropuerto De Valladolid Villanubla Castile And Leon Spain",
  "VLN": "Aeropuerto Internacional Arturo Michelena Valencia Venezuela",
  "VNO": "Tarptautinis Vilniaus Oro Uostas Vilnius Lithuania",
  "VNS": "Lal Bahadur Shastri International Airport Varanasi Benares Utter Pradesh Up India",
  "VNY": "Van Nuys Airport Los Angeles California Ca Usa",
  "VOG": "Volgograd International Airport Russia",
  "VOZ": "Voronezh-chertovitskoye International Airport Voronezh Lipetsk Russia",
  "VPS": "Destin–fort Walton Beach Airport Fort Destin Florida Fl Usa",
  "VRA": "Juan Gualberto Gómez Airport Varadero Matanzas Cuba",
  "VRN": "Aeroporto Di Verona-villafranca Airport Verona Villafranca Italy",
  "VTE": "Wattay International Airport Vientiane Laos",
  "VTZ": "Visakhapatnam International Airport Andhra Pradesh Ap India",
  "VVI": "Aeropuerto Internacional Viru International Airport Santa Cruz De La Sierra Bolivia",
  "WAT": "Waterford Airport Ireland",
  "WAW": "Lotnisko Chopina W Warszawie Warsaw Chopin Poland",
  "WDH": "Hosea Kutako International Airport Windhoek Namibia",
  "WGP": "Bandar Udara Umbu Mehang Kunda Airport Waingapu Sumba East Nusa Tenggara Indonesia",
  "WLG": "Wellington International Airport Rongotai New Zealand",
  "WMI": "Mazowiecki Port Lotniczy Warsaw Nowy Dwór Poland",
  "WRO": "Port Lotniczy Wrocław Im. Mikołaja Kopernika Wroclaw Lower Silesian Voivodeship Poland",
  "WUH": "Wuhan Tianhe International Airport China",
  "WUX": "Sunan Shuofang International Airport Wuxi Suzhou China",
  "XCH": "Christmas Island Airport Australia",
  "XFW": "Airbus-werk Hamburg-finkenwerder Hamburg Finkenwerder Germany",
  "XIY": "Xi'an Xianyang International Airport Shaanxi China",
  "XMN": "Xiamen Gaoqi International Airport Huli District China",
  "XNA": "Northwest Arkansas Regional Airport Fayetteville Springdale Ar Usa",
  "XNN": "Xining Caojiabao Airport Huzhu Qinghai China",
  "XRY": "Aeropuerto De Jerez La Frontera Spain",
  "YAM": "Sault Ste. Marie Airport Ontario On Canada",
  "YAP": "International Airport Micronesia",
  "YAZ": "Tofino/long Beach Airport Tofino Long British Columbia Bc Canada",
  "YCD": "Nanaimo Airport Cassidy British Columbia Bc Canada",
  "YDT": "Boundary Bay Airport Vancouver Delta British Columbia Bc Canada",
  "YEG": "Edmonton International Airport Alberta Ab Canada",
  "YFB": "Iqaluit Airport Nunavut Nu Canada",
  "YGO": "Gods Lake Narrows Airport Manitoba Mb Canada",
  "YHK": "Gjoa Haven Airport Nunavut Nu Canada",
  "YHM": "John C. Munro Hamilton International Airport Toronto Ontario On Canada",
  "YHZ": "Halifax Stanfield International Airport Enfield Nova Scotia Ns Canada",
  "YIP": "Willow Run Airport Ypsilanti Michigan Mi Usa",
  "YJS": "Samjiyŏn Airport Ryanggang Korea North",
  "YLT": "Alert Airport Nunavut Nu Canada",
  "YLW": "Kelowna International Airport British Columbia Bc Canada",
  "YMM": "Fort Mcmurray International Airport Alberta Ab Canada",
  "YMX": "Aéroport International Montréal–mirabel Montreal Mirabel Quebec Qc Canada",
  "YNB": "Prince Abdul Mohsin Bin Abdulaziz Airport Yanbu' Al Bahr Madinah Province Saudi Arabia",
  "YNG": "Youngstown–warren Regional Airport Youngstown Warren Ohio Oh Usa",
  "YON": "Yongphulla Airport Trashigang Bhutan",
  "YOO": "Oshawa Executive Airport Toronto Ontario On Canada",
  "YOW": "Ottawa Macdonald–cartier International Airport Ontario On Canada",
  "YQB": "Aéroport International Jean-lesage De Québec City Quebec Qc Canada",
  "YQM": "Greater Moncton International Airport Dieppe New Brunswick Nb Canada",
  "YQR": "Regina International Airport Saskatchewan Sk Canada",
  "YQT": "Thunder Bay International Airport Ontario On Canada",
  "YQX": "Gander International Airport Newfoundland And Labrador Nl Canada",
  "YQY": "Sydney/j.a. Douglas Mccurdy Airport Sydney Nova Scotia Ns Canada",
  "YSB": "Sudbury Airport Ontario On Canada",
  "YSJ": "Aéroport De Saint John New Brunswick Nb Canada",
  "YTZ": "Billy Bishop Toronto City Airport Division Ontario On Canada",
  "YUL": "Aéroport International Pierre-elliott-trudeau De Montréal Montréal–pierre Elliott Trudeau Montreal Dorval Quebec Qc Canada",
  "YUM": "Yuma International Airport Arizona Az Usa",
  "YVR": "Vancouver International Airport Richmond British Columbia Bc Canada",
  "YWG": "James Armstrong Richardson International Airport Winnipeg Manitoba Mb Canada",
  "YXE": "Saskatoon John G. Diefenbaker International Airport Saskatchewan Sk Canada",
  "YXH": "Medicine Hat Airport Alberta Ab Canada",
  "YXU": "London International Airport Ontario On Canada",
  "YXX": "Abbotsford International Airport British Columbia Bc Canada",
  "YXY": "Erik Nielsen Whitehorse International Airport Yukon Yt Canada",
  "YYC": "Calgary International Airport Alberta Ab Canada",
  "YYD": "Smithers Regional Airport British Columbia Bc Canada",
  "YYJ": "Victoria International Airport British Columbia Bc Canada",
  "YYT": "St. John’s International Airport Newfoundland And Labrador Nl Canada",
  "YYZ": "Pearson International Airport Toronto Malton Ontario On Canada",
  "YZF": "Yellowknife Airport Northwest Territories Nt Canada",
  "ZAD": "Zračna Luka Zadar/zemunik Zadar Croatia",
  "ZAG": "Međunarodna Zračna Luka Zagreb Pleso Croatia",
  "ZAZ": "Aeropuerto De Zaragoza Spain",
  "ZCL": "Aeropuerto Internacional General Leobardo C. Ruiz Zacatecas Fresnillo Mexico",
  "ZIA": "Zhukovsky International Airport Moscow Russia",
  "ZIH": "Aeropuerto Internacional De Ixtapa-zihuatanejo Zihuatanejo Ixtapa Guerrero Gr Mexico",
  "ZLO": "Aeropuerto Internacional Playa De Oro International Airport Manzanillo Colima Cl Mexico",
  "ZQN": "Queenstown Airport Frankton New Zealand",
  "ZRH": "Flughafen Zürich Zurich Switzerland"
};
