version: '3.8'

services:
  mysql:
    build:
      context: ../db
      dockerfile: Dockerfile
    container_name: booking_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking_system
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: booking_adminer
    restart: unless-stopped
    ports:
      - "8085:8080"
    depends_on:
      - mysql

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: booking_backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: booking_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
