export enum Role {
  AGENT = 'AGENT',
  COMPANY_ADMIN = 'COMPANY_ADMIN',
  MAIN_COMPANY_ADMIN = 'MAIN_COMPANY_ADMIN',
  ADMIN = 'ADMIN' // Keeping ADMIN for legacy/backward compatibility during migration
}

export enum Permission {
  // Bookings & Itineraries
  CREATE_BOOKING = 'CREATE_BOOKING',
  READ_BOOKING = 'READ_BOOKING',
  UPDATE_BOOKING = 'UPDATE_BOOKING',
  DELETE_BOOKING = 'DELETE_BOOKING',

  // Client Records
  CREATE_CLIENT = 'CREATE_CLIENT',
  READ_CLIENT = 'READ_CLIENT',
  UPDATE_CLIENT = 'UPDATE_CLIENT',
  DELETE_CLIENT = 'DELETE_CLIENT',

  // Vendor Records
  CREATE_VENDOR = 'CREATE_VENDOR',
  READ_VENDOR = 'READ_VENDOR',
  UPDATE_VENDOR = 'UPDATE_VENDOR',
  DELETE_VENDOR = 'DELETE_VENDOR',

  // Agency Dashboard / KPIs
  READ_DASHBOARD = 'READ_DASHBOARD',

  // Team / User Management
  CREATE_USER = 'CREATE_USER',
  READ_USER = 'READ_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // Financial Transactions / Refunds
  CREATE_TRANSACTION = 'CREATE_TRANSACTION',
  READ_TRANSACTION = 'READ_TRANSACTION',
  UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
  DELETE_TRANSACTION = 'DELETE_TRANSACTION',

  // System Settings
  MANAGE_SETTINGS = 'MANAGE_SETTINGS',

  // Attendance
  CREATE_ATTENDANCE = 'CREATE_ATTENDANCE',
  READ_ATTENDANCE = 'READ_ATTENDANCE',
  UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE',
  DELETE_ATTENDANCE = 'DELETE_ATTENDANCE',

  // Payroll
  CREATE_PAYROLL = 'CREATE_PAYROLL',
  READ_PAYROLL = 'READ_PAYROLL',
  UPDATE_PAYROLL = 'UPDATE_PAYROLL',
  DELETE_PAYROLL = 'DELETE_PAYROLL',

  // Document Studio
  CREATE_TEMPLATE = 'CREATE_TEMPLATE',
  READ_TEMPLATE = 'READ_TEMPLATE',
  UPDATE_TEMPLATE = 'UPDATE_TEMPLATE',
  DELETE_TEMPLATE = 'DELETE_TEMPLATE'
}
