name: Deploy Travel System

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST || vars.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            cd /home/faisal/travel_management_system
            echo "Pulling latest code..."
            git pull origin main
            echo "Starting Docker containers..."
            docker compose up -d --build
            echo "Cleaning unused images..."
            docker image prune -f
            echo "Deployment complete"
